# ECC3479 notebook

**Matched Tables Using House Prices + ABS Population**

Create two suburb-level tables for 2015 to 2024 using:
- `data/clean/suburbs_house_prices_2015_2024_wide_complete.csv`
- `data/raw/abs_population.xlsx` (Table 1, SA2 population)

The merge keeps all suburbs in the house prices file and brings in matching ABS SA2-name rows where available. Suburbs not included in the analysis were those that did not appear in either of the datasets.

In [48]:
from pathlib import Path
import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

project_root = Path.cwd()
if not (project_root / "data").exists():
    project_root = project_root.parent

house_file = project_root / "data" / "clean" / "suburbs_house_prices_2015_2024_wide_complete.csv"
abs_file = project_root / "data" / "raw" / "abs_population.xlsx"

years = [str(y) for y in range(2015, 2025)]

# ----------------------------
# 1) House prices table
# ----------------------------
house = pd.read_csv(house_file)
house = house.rename(columns={"Suburb": "suburb"})
house["suburb"] = (
    house["suburb"]
    .astype(str)
    .str.strip()
    .str.replace(r"\\s+", " ", regex=True)
    .str.upper()
    )

missing_house_years = [y for y in years if y not in house.columns]
if missing_house_years:
    raise ValueError(f"Missing house-price year columns: {missing_house_years}")

for y in years:
    house[y] = pd.to_numeric(house[y], errors="coerce")

table_house_prices = (
    house[["suburb"] + years]
    .drop_duplicates(subset=["suburb"], keep="first")
    .sort_values("suburb")
    .reset_index(drop=True)
)

# ----------------------------
# 2) Population table from ABS Table 1
# ----------------------------
# ABS Table 1 contains metadata rows; the real headers are around rows 5-6.
pop_raw = pd.read_excel(abs_file, sheet_name="Table 1", header=None)

header_top = pop_raw.iloc[4]
header_bottom = pop_raw.iloc[5]
combined_cols = []
for top, bottom in zip(header_top, header_bottom):
    if pd.notna(top) and str(top).strip().lower() != "nan":
        combined_cols.append(str(top).strip())
    else:
        combined_cols.append(str(bottom).strip())

pop = pop_raw.iloc[6:].copy()
pop.columns = combined_cols

needed_cols = ["SA2 name"] + years
missing_pop_cols = [c for c in needed_cols if c not in pop.columns]
if missing_pop_cols:
    raise ValueError(f"Missing ABS columns: {missing_pop_cols}")

pop = pop[needed_cols].rename(columns={"SA2 name": "suburb"})
pop["suburb"] = (
    pop["suburb"]
    .astype(str)
    .str.strip()
    .str.replace(r"\\s+", " ", regex=True)
    .str.upper()
    )

for y in years:
    pop[y] = pd.to_numeric(pop[y], errors="coerce")

pop = (
    pop
    .dropna(subset=["suburb"])
    .drop_duplicates(subset=["suburb"], keep="first")
    .reset_index(drop=True)
)

# Keep all house-price suburbs, bring matching ABS values where suburb names align.
table_population_density = (
    table_house_prices[["suburb"]]
    .merge(pop, on="suburb", how="left")
    .sort_values("suburb")
    .reset_index(drop=True)
)

# Remove suburbs from table_population_density that have NaN for all year columns
# Then also remove those suburbs from table_house_prices to keep both tables aligned
rows_with_all_nans = table_population_density[years].isna().all(axis=1)
suburbs_to_remove = table_population_density.loc[rows_with_all_nans, "suburb"].tolist()

table_population_density = table_population_density[~rows_with_all_nans].reset_index(drop=True)
table_house_prices = table_house_prices[~table_house_prices["suburb"].isin(suburbs_to_remove)].reset_index(drop=True)

# Keep only the chosen suburbs that exist in both tables (expected: 172 suburbs).
chosen_suburbs = sorted(set(table_house_prices["suburb"]).intersection(set(table_population_density["suburb"])))
table_house_prices = table_house_prices[table_house_prices["suburb"].isin(chosen_suburbs)].sort_values("suburb").reset_index(drop=True)
table_population_density = table_population_density[table_population_density["suburb"].isin(chosen_suburbs)].sort_values("suburb").reset_index(drop=True)

# Optional: save outputs
house_out = project_root / "data" / "clean" / "matched_houses_population_2015_2024_prices.csv"
pop_out = project_root / "data" / "clean" / "matched_houses_population_2015_2024_population.csv"
table_house_prices.to_csv(house_out, index=False)
table_population_density.to_csv(pop_out, index=False)

matched_count = len(table_population_density)
print(f"House-price suburbs total (Table 1): {len(table_house_prices)}")
print(f"Population suburbs total (Table 2): {len(table_population_density)}")
print(f"Chosen suburbs kept in both tables: {len(chosen_suburbs)}")
print(f"Removed suburbs with no ABS data: {len(suburbs_to_remove)}")
print(f"Saved: {house_out}")
print(f"Saved: {pop_out}")

print("\nTable 1: Suburbs with matching house prices (2015-2024)")
display(table_house_prices)

print("\nTable 2: Suburbs with matching ABS population values (2015-2024)")
print("(Named as requested: population density table)")
display(table_population_density)

House-price suburbs total (Table 1): 172
Population suburbs total (Table 2): 172
Chosen suburbs kept in both tables: 172
Removed suburbs with no ABS data: 314
Saved: c:\Users\samantha\Desktop\uni ૮₍•᷄ ࡇ•᷅₎ა\Y3S1\ECC3479\ECC3479-project\ecc3479-project\ECC3479-project (data + GitHub repo)\data\clean\matched_houses_population_2015_2024_prices.csv
Saved: c:\Users\samantha\Desktop\uni ૮₍•᷄ ࡇ•᷅₎ა\Y3S1\ECC3479\ECC3479-project\ecc3479-project\ECC3479-project (data + GitHub repo)\data\clean\matched_houses_population_2015_2024_population.csv

Table 1: Suburbs with matching house prices (2015-2024)

,suburb,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,ABBOTSFORD,925000.0,1187500.0,1280000.0,1192500.0,1050000.0,1200000.0,1365000.0,1346000.0,1257500.0,1232500.0
1,AIRPORT WEST,635000.0,742000.0,845000.0,845000.0,795000.0,812500.0,960000.0,911000.0,952500.0,940000.0
2,ALBERT PARK,1700000.0,1775000.0,2150000.0,2070000.0,1990000.0,1900000.0,2355000.0,2475000.0,2287500.0,2225000.0
3,ALBION,481000.0,593000.0,730000.0,755000.0,675000.0,727500.0,832500.0,830000.0,765000.0,735000.0
4,ALEXANDRA,285000.0,275000.0,291500.0,335000.0,325000.0,380000.0,440000.0,550000.0,477500.0,512500.0
5,ALFREDTON,340500.0,375000.0,412500.0,439000.0,480000.0,512000.0,605000.0,650000.0,640000.0,605000.0
6,ALTONA,718000.0,832500.0,950000.0,932500.0,890000.0,914000.0,1162500.0,1180000.0,1142500.0,1170000.0
7,ALTONA MEADOWS,440000.0,495000.0,626500.0,631500.0,615000.0,640000.0,720000.0,740000.0,690000.0,717000.0
8,ALTONA NORTH,642500.0,725000.0,825000.0,835000.0,790000.0,832500.0,900500.0,940000.0,881000.0,917000.0
9,ARARAT,210000.0,204500.0,199000.0,199000.0,215000.0,244000.0,315000.0,380000.0,375000.0,380000.0
10,ARMADALE,2172500.0,2364000.0,2300000.0,2341500.0,2490000.0,2625000.0,2700000.0,2735500.0,2740000.0,2380000.0
11,ASCOT VALE,885000.0,1010000.0,1185000.0,1197500.0,1100000.0,1210000.0,1245000.0,1325000.0,1300500.0,1300000.0
12,AVOCA,182500.0,165000.0,212500.0,220000.0,219500.0,290000.0,325000.0,367500.0,350000.0,390000.0
13,AVONDALE HEIGHTS,650000.0,750000.0,845500.0,830000.0,810000.0,842500.0,965500.0,990000.0,938500.0,980500.0
14,BACCHUS MARSH,355000.0,376000.0,415500.0,480000.0,500000.0,520000.0,597000.0,665000.0,640000.0,610000.0
15,BAIRNSDALE,246500.0,255000.0,272500.0,279000.0,274000.0,290000.0,350000.0,440000.0,435000.0,430000.0
16,BALWYN,2210000.0,2180000.0,2340000.0,2420000.0,2377500.0,2260000.0,2750000.0,2862000.0,2965000.0,2868000.0
17,BALWYN NORTH,1850000.0,1800000.0,1950000.0,1810000.0,1720000.0,1900000.0,2255500.0,2229000.0,2382500.0,2310000.0
18,BANNOCKBURN,393000.0,382000.0,430000.0,487500.0,530000.0,555000.0,680000.0,729500.0,710000.0,712500.0
19,BAYSWATER,632500.0,693000.0,800500.0,753000.0,720000.0,745500.0,870000.0,902000.0,870000.0,862000.0
20,BAYSWATER NORTH,580000.0,628000.0,737500.0,713000.0,695000.0,734500.0,855500.0,869500.0,843000.0,899000.0
21,BEAUFORT,205000.0,237500.0,220000.0,225000.0,242500.0,325000.0,390000.0,415000.0,405000.0,380000.0
22,BEAUMARIS,1345000.0,1455000.0,1611000.0,1674000.0,1587500.0,1725000.0,2100000.0,2061000.0,2055000.0,2061000.0
23,BEECHWORTH,332000.0,345000.0,399000.0,400000.0,478500.0,487500.0,645000.0,707000.0,720000.0,780000.0
24,BELMONT,395000.0,430000.0,500000.0,545000.0,545000.0,605000.0,730000.0,740000.0,682000.0,700000.0
25,BENALLA,222500.0,231500.0,250000.0,284000.0,290000.0,302000.0,394000.0,430500.0,425000.0,440000.0
26,BENDIGO,372000.0,400000.0,400000.0,400000.0,420000.0,500000.0,600000.0,690000.0,540000.0,620000.0
27,BROADMEADOWS,370000.0,416500.0,546000.0,575000.0,525500.0,551500.0,590000.0,600000.0,560000.0,585000.0
28,BROOKFIELD,340000.0,360000.0,425000.0,491500.0,445000.0,500000.0,539000.0,570000.0,560000.0,550000.0
29,BRUNSWICK EAST,888000.0,998000.0,1150000.0,1170000.0,1011500.0,1286500.0,1440000.0,1350000.0,1403000.0,1353000.0
30,BRUNSWICK WEST,863000.0,1002500.0,1155000.0,1160000.0,1061000.0,1180000.0,1324000.0,1285500.0,1277500.0,1327500.0
31,BULLEEN,1095000.0,1170000.0,1300000.0,1230000.0,1105000.0,1177000.0,1355000.0,1386000.0,1400000.0,1300000.0
32,BUNINYONG,364500.0,381000.0,470000.0,467500.0,475000.0,587500.0,666000.0,770000.0,680000.0,698500.0
33,BURNSIDE,415000.0,518500.0,572500.0,605000.0,605000.0,660000.0,720000.0,780000.0,752500.0,730000.0
34,BURNSIDE HEIGHTS,460000.0,522000.0,590000.0,633000.0,591000.0,652500.0,701000.0,749000.0,740000.0,749000.0
35,BURWOOD EAST,982000.0,1021000.0,1126500.0,1005000.0,1106000.0,1168500.0,1250500.0,1259000.0,1281000.0,1285500.0
36,CAIRNLEA,540000.0,608500.0,710000.0,734000.0,752500.0,807500.0,850000.0,941500.0,940000.0,932500.0
37,CAMBERWELL,1912500.0,2090000.0,2300000.0,2155000.0,2070000.0,2072500.0,2569000.0,2650000.0,2538000.0,2600000.0
38,CAMPERDOWN,218000.0,217500.0,240000.0,235000.0,280000.0,292500.0,362500.0,415000.0,470000.0,429000.0
39,CARLTON,830000.0,1050000.0,1470000.0,1625000.0,1308000.0,1452500.0,1492500.0,1512500.0,1500000.0,1390000.0
40,CARNEGIE,1300000.0,1348500.0,1510000.0,1445000.0,1313500.0,1420000.0,1776000.0,1687500.0,1675000.0,1715000.0
41,CAROLINE SPRINGS,480000.0,530000.0,611000.0,620000.0,620000.0,650000.0,720000.0,750000.0,731000.0,743500.0
42,CARRUM DOWNS,370000.0,430000.0,525000.0,575000.0,537000.0,575000.0,665000.0,705000.0,697500.0,716500.0
43,CASTLEMAINE,380000.0,410000.0,435000.0,499000.0,520000.0,556500.0,680500.0,737000.0,727000.0,747000.0
44,CHELSEA HEIGHTS,598000.0,641000.0,750000.0,778000.0,750000.0,805000.0,977500.0,935000.0,906500.0,932500.0
45,CHIRNSIDE PARK,542500.0,627000.0,735000.0,700000.0,680500.0,750000.0,900000.0,920000.0,900000.0,890500.0
46,CHURCHILL,172500.0,182000.0,175000.0,180000.0,185000.0,226000.0,305000.0,360000.0,345000.0,355000.0
47,CLAYTON SOUTH,687500.0,755000.0,850500.0,850000.0,832000.0,830000.0,982500.0,975000.0,950000.0,961500.0
48,CLIFTON SPRINGS,345000.0,365000.0,420000.0,472000.0,485000.0,518500.0,666000.0,710000.0,670000.0,672000.0
49,COBRAM,236000.0,265000.0,255000.0,255000.0,272500.0,300000.0,370000.0,414000.0,437500.0,405000.0
50,COBURG NORTH,665000.0,780000.0,822000.0,814000.0,805000.0,899000.0,1008500.0,1020000.0,985000.0,1071000.0
51,COLAC,246500.0,259500.0,282500.0,320000.0,315000.0,350000.0,420000.0,500000.0,481000.0,463000.0
52,COLLINGWOOD,914000.0,920000.0,1205000.0,1110000.0,1060000.0,1155000.0,1251500.0,1289000.0,1225000.0,1184000.0
53,CRANBOURNE,360000.0,406000.0,510000.0,540000.0,500000.0,510000.0,618000.0,660000.0,655000.0,660000.0
54,CRANBOURNE WEST,350000.0,410000.0,510500.0,540000.0,508000.0,510000.0,600000.0,680000.0,660000.0,685000.0
55,CROYDON,605000.0,695000.0,809000.0,792500.0,735000.0,785000.0,920000.0,900000.0,920000.0,923000.0
56,CROYDON SOUTH,600000.0,655000.0,800000.0,757500.0,715500.0,740000.0,890000.0,864000.0,890000.0,915000.0
57,DANDENONG NORTH,481000.0,551000.0,633500.0,640000.0,606500.0,640000.0,729000.0,740000.0,725000.0,756000.0
58,DAYLESFORD,442500.0,464000.0,502000.0,552500.0,592500.0,692500.0,835000.0,910000.0,899000.0,847500.0
59,DEER PARK,390000.0,441000.0,552500.0,580000.0,550000.0,580000.0,630000.0,635000.0,640000.0,657500.0
60,DELACOMBE,290000.0,319000.0,325000.0,360000.0,390000.0,410000.0,525000.0,570000.0,527500.0,525000.0
61,DELAHEY,400000.0,458000.0,545000.0,575000.0,530000.0,575000.0,645000.0,650000.0,639000.0,642500.0
62,DERRIMUT,466000.0,530000.0,635000.0,615000.0,649000.0,658000.0,715000.0,770000.0,740000.0,750000.0
63,DIGGERS REST,325000.0,360000.0,440500.0,500000.0,515000.0,560000.0,613000.0,657500.0,660000.0,655000.0
64,DINGLEY VILLAGE,690000.0,775500.0,887000.0,840500.0,810000.0,934000.0,1050000.0,1112000.0,1090000.0,1124500.0
65,DONCASTER,1176000.0,1297500.0,1368000.0,1320000.0,1270000.0,1280000.0,1500000.0,1500000.0,1547500.0,1480500.0
66,DOVETON,348000.0,405000.0,490000.0,543500.0,472000.0,500000.0,579000.0,625000.0,561500.0,600000.0
67,DROMANA,551000.0,583000.0,690000.0,786000.0,715000.0,762500.0,1000000.0,1100000.0,1055000.0,1000000.0
68,DROUIN,320000.0,347000.0,390000.0,455000.0,440000.0,467000.0,565000.0,620000.0,621500.0,605000.0
69,FLEMINGTON,830000.0,918000.0,1100000.0,926500.0,1000000.0,1028500.0,1250000.0,1103500.0,1017000.0,1085000.0
70,FLINDERS,839000.0,1225000.0,1525000.0,1697500.0,1670000.0,2085000.0,2667500.0,3342000.0,2800000.0,2500000.0
71,FOOTSCRAY,690500.0,775000.0,883500.0,899000.0,812000.0,870000.0,962500.0,993000.0,920000.0,960000.0
72,FOREST HILL,892000.0,933500.0,1060000.0,935000.0,900000.0,986000.0,1207500.0,1155500.0,1251000.0,1200000.0
73,FOSTER,325000.0,315000.0,320000.0,333500.0,330000.0,387500.0,457500.0,595000.0,590000.0,567500.0
74,FRANKSTON,426000.0,474000.0,600000.0,605000.0,581000.0,621500.0,750000.0,764500.0,736000.0,740000.0
75,FRANKSTON NORTH,297000.0,352000.0,470000.0,502000.0,423000.0,450000.0,580000.0,610000.0,574000.0,595000.0
76,FRANKSTON SOUTH,620000.0,690000.0,815500.0,855000.0,817500.0,860000.0,1150000.0,1200000.0,1160000.0,1150000.0
77,GEELONG,607500.0,590000.0,735000.0,757500.0,720000.0,883500.0,950000.0,900000.0,991500.0,870000.0
78,GISBORNE,550000.0,635000.0,655000.0,770000.0,730000.0,810000.0,898500.0,1052500.0,1000000.0,915000.0
79,GOWANBRAE,573000.0,619000.0,790000.0,727500.0,700500.0,739000.0,940000.0,902500.0,865000.0,1025000.0
80,GREENSBOROUGH,635000.0,717000.0,830000.0,815000.0,798000.0,850000.0,1001000.0,1000000.0,980000.0,1020000.0
81,HADFIELD,550000.0,624500.0,740500.0,741500.0,730000.0,745000.0,890000.0,888000.0,850000.0,850500.0
82,HALLAM,424000.0,455000.0,580000.0,630000.0,550000.0,600000.0,700000.0,720000.0,720000.0,750000.0
83,HAMPTON,1650000.0,1800000.0,2020000.0,1905000.0,1900000.0,2000000.0,2420000.0,2350000.0,2385000.0,2480000.0
84,HAWTHORN EAST,1850000.0,1890000.0,2350000.0,2221500.0,2087500.0,2383000.0,2280000.0,2655000.0,2770000.0,2585000.0
85,HEATHCOTE,240000.0,268500.0,275000.0,310000.0,335000.0,365000.0,390000.0,480000.0,485000.0,502500.0
86,HEIDELBERG WEST,580000.0,630000.0,730000.0,700000.0,670000.0,719000.0,810000.0,803500.0,751000.0,797000.0
87,HIGHTON,505000.0,555000.0,622500.0,681000.0,690000.0,744000.0,887000.0,950000.0,913500.0,863500.0
88,KEILOR,703000.0,805000.0,845000.0,817000.0,836500.0,885000.0,1070500.0,1000000.0,1132500.0,1110000.0
89,KEILOR DOWNS,496500.0,562000.0,670000.0,661000.0,630000.0,660000.0,765000.0,759000.0,770000.0,766500.0
90,KEILOR EAST,651000.0,720000.0,843000.0,830000.0,835000.0,842000.0,1000000.0,1000000.0,990000.0,1055000.0
91,KERANG,152000.0,167000.0,160000.0,177000.0,170000.0,200000.0,239000.0,275500.0,282500.0,310000.0
92,KIALLA,367500.0,374000.0,390000.0,418000.0,450000.0,482500.0,543000.0,640000.0,650000.0,670000.0
93,KILSYTH,548500.0,620000.0,698500.0,685500.0,645000.0,677500.0,781000.0,841500.0,810000.0,815000.0
94,KINGLAKE,340000.0,346000.0,458000.0,480000.0,555000.0,600000.0,640000.0,770000.0,662500.0,775000.0
95,KINGSBURY,560000.0,610000.0,731000.0,730000.0,660000.0,732500.0,848500.0,782000.0,792500.0,862500.0
96,KOO WEE RUP,345000.0,400000.0,450500.0,508500.0,550000.0,540000.0,610000.0,700000.0,670000.0,666500.0
97,KORUMBURRA,262500.0,257500.0,292000.0,317500.0,320000.0,391000.0,480000.0,525000.0,550000.0,550000.0
98,KYABRAM,240000.0,234000.0,239000.0,261000.0,263000.0,280000.0,319500.0,400000.0,455000.0,450000.0
99,KYNETON,425500.0,455000.0,495000.0,550000.0,595000.0,614000.0,755000.0,897500.0,775000.0,780000.0
100,LAKES ENTRANCE,255500.0,280000.0,281500.0,328000.0,300000.0,350000.0,422500.0,540000.0,510000.0,520000.0
101,LANGWARRIN,450000.0,503000.0,600000.0,642500.0,610000.0,660000.0,805000.0,860000.0,835000.0,858000.0
102,LARA,348000.0,355000.0,430000.0,515000.0,495000.0,535000.0,682500.0,700000.0,685000.0,678000.0
103,LAVERTON,377500.0,429000.0,535000.0,579000.0,529000.0,560000.0,605000.0,610000.0,582500.0,590000.0
104,LEONGATHA,305000.0,305000.0,320000.0,360000.0,370000.0,426000.0,505000.0,589000.0,580000.0,572500.0
105,LEOPOLD,365000.0,407000.0,447000.0,500500.0,510000.0,535000.0,652000.0,709000.0,682500.0,662000.0
106,LYSTERFIELD,780000.0,857500.0,995500.0,976500.0,956500.0,1009500.0,1132000.0,1267500.0,1307500.0,1331000.0
107,MACEDON,532500.0,585000.0,696000.0,815000.0,800000.0,883000.0,1130000.0,1073000.0,1105000.0,1100000.0
108,MAFFRA,230000.0,258000.0,251500.0,261500.0,255000.0,315000.0,337000.0,376500.0,425000.0,435000.0
109,MAIDEN GULLY,430000.0,477000.0,471000.0,495500.0,514000.0,579000.0,725000.0,760000.0,797500.0,760000.0
110,MALVERN EAST,1610000.0,1729000.0,1824000.0,1900000.0,1789000.0,1895000.0,2112500.0,2282500.0,2192500.0,2057500.0
111,MARIBYRNONG,837500.0,940000.0,1056000.0,1050000.0,961500.0,936500.0,1165000.0,1170000.0,1110000.0,1250000.0
112,MEADOW HEIGHTS,350500.0,370000.0,451000.0,510000.0,474000.0,499000.0,557500.0,580000.0,561000.0,595000.0
113,MELTON,255000.0,280500.0,369000.0,415000.0,385000.0,390000.0,455000.0,500000.0,470500.0,471000.0
114,MELTON WEST,295000.0,330000.0,409000.0,453000.0,428000.0,470000.0,515000.0,551000.0,550000.0,525000.0
115,MENTONE,950000.0,982500.0,1097500.0,1080000.0,1031000.0,1050000.0,1370000.0,1475000.0,1332500.0,1320000.0
116,MERBEIN,180000.0,170000.0,183500.0,180000.0,210000.0,201500.0,227500.0,320000.0,300000.0,345000.0
117,MURRUMBEENA,1204000.0,1286000.0,1420000.0,1343500.0,1241500.0,1405000.0,1695000.0,1670000.0,1650000.0,1706000.0
118,MYRTLEFORD,242000.0,270500.0,265000.0,295000.0,325000.0,385000.0,530000.0,609000.0,592500.0,582500.0
119,NAGAMBIE,360500.0,336000.0,330000.0,385000.0,414000.0,460000.0,545000.0,655000.0,645000.0,630000.0
120,NARRE WARREN NORTH,771500.0,900000.0,1108000.0,1180000.0,1070000.0,1167500.0,1421500.0,1600000.0,1580000.0,1685000.0
121,NEWPORT,825000.0,950000.0,1080000.0,1059000.0,1055000.0,1090000.0,1286500.0,1280000.0,1275000.0,1300000.0
122,NOBLE PARK NORTH,491500.0,563000.0,640000.0,660000.0,610000.0,655500.0,750000.0,795000.0,737500.0,772500.0
123,NORLANE,216000.0,236500.0,290000.0,355000.0,350000.0,372000.0,450000.0,481500.0,455000.0,462000.0
124,NORTH MELBOURNE,943000.0,1200000.0,1380000.0,1185000.0,1375000.0,1151500.0,1335000.0,1381000.0,1220000.0,1311000.0
125,NUMURKAH,219000.0,195000.0,219000.0,225000.0,250000.0,239000.0,310000.0,350000.0,360000.0,394500.0
126,NUNAWADING,880000.0,970000.0,1090000.0,986000.0,951000.0,1038500.0,1250000.0,1146000.0,1189000.0,1152500.0
127,OAK PARK,660000.0,822500.0,853500.0,878500.0,840000.0,911500.0,1150000.0,1140000.0,1085000.0,1122500.0
128,OCEAN GROVE,516500.0,555000.0,637000.0,691000.0,695000.0,790000.0,975500.0,1136500.0,989000.0,970000.0
129,ORBOST,145000.0,162500.0,159000.0,165000.0,185500.0,220000.0,240000.0,344000.0,340000.0,356000.0
130,PASCOE VALE,720000.0,805000.0,891000.0,901000.0,855000.0,947500.0,1050000.0,1110000.0,1025000.0,1047500.0
131,PASCOE VALE SOUTH,745000.0,840000.0,975000.0,955000.0,950000.0,1006000.0,1299500.0,1157500.0,1130000.0,1222500.0
132,PAYNESVILLE,305000.0,309000.0,336500.0,353000.0,346000.0,397000.0,465000.0,565000.0,515000.0,502500.0
133,PORT MELBOURNE,1252500.0,1380000.0,1485000.0,1488000.0,1400000.0,1600000.0,1802500.0,1646000.0,1755000.0,1600000.0
134,PORTARLINGTON,409000.0,460000.0,515000.0,640000.0,625000.0,690000.0,829500.0,985000.0,932500.0,890000.0
135,PORTLAND,220000.0,220000.0,230000.0,234500.0,266000.0,295000.0,370000.0,450000.0,439000.0,415000.0
136,RED CLIFFS,175000.0,165000.0,223500.0,211500.0,217500.0,270000.0,311000.0,325000.0,335000.0,397500.0
137,RIDDELLS CREEK,456500.0,500000.0,580000.0,675000.0,710000.0,680000.0,870000.0,872500.0,865000.0,815000.0
138,RINGWOOD,777500.0,837500.0,910500.0,896500.0,801000.0,900000.0,1018000.0,1038000.0,999500.0,1025000.0
139,RINGWOOD EAST,750000.0,806000.0,901000.0,881000.0,809000.0,861000.0,1050000.0,975000.0,1000000.0,1065000.0
140,RINGWOOD NORTH,783500.0,844000.0,960500.0,920000.0,870000.0,957500.0,1183000.0,1200000.0,1217500.0,1207500.0
141,ROBINVALE,184500.0,170000.0,197000.0,220000.0,231500.0,235000.0,340000.0,315000.0,350000.0,390000.0
142,ROCHESTER,235000.0,239000.0,242500.0,236000.0,255000.0,237000.0,350000.0,440000.0,262500.0,300000.0
143,ROMSEY,420000.0,428000.0,470000.0,550000.0,580500.0,630000.0,780000.0,839000.0,755000.0,785000.0
144,ROSEDALE,197000.0,230000.0,247000.0,280000.0,247000.0,250000.0,365000.0,420000.0,475000.0,452000.0
145,RUSHWORTH,177000.0,200000.0,192500.0,198000.0,205000.0,226000.0,301000.0,352500.0,367000.0,385000.0
146,RUTHERGLEN,230000.0,255000.0,262000.0,270000.0,282500.0,350000.0,402500.0,486500.0,479000.0,550000.0
147,SALE,298000.0,295500.0,300000.0,309500.0,325000.0,345000.0,399000.0,487000.0,480000.0,485000.0
148,SEABROOK,456000.0,509000.0,635000.0,672500.0,626500.0,652500.0,730000.0,755000.0,741500.0,764500.0
149,SEYMOUR,225000.0,242500.0,277000.0,295000.0,300000.0,325000.0,390000.0,450000.0,467500.0,445000.0
150,SOMERVILLE,425000.0,465000.0,580000.0,615000.0,600000.0,640000.0,780000.0,812000.0,765000.0,812500.0
151,SOUTH MELBOURNE,1310000.0,1595000.0,1532500.0,1465000.0,1355000.0,1580000.0,1710000.0,1882500.0,1640000.0,1532500.0
152,SPRINGVALE,629500.0,685000.0,750000.0,780000.0,746500.0,785000.0,855000.0,886500.0,870000.0,850000.0
153,SPRINGVALE SOUTH,562000.0,630000.0,720000.0,720000.0,679000.0,725000.0,800000.0,810000.0,810500.0,850500.0
154,ST ARNAUD,141000.0,142500.0,145000.0,145000.0,175000.0,170000.0,225000.0,310000.0,280000.0,275000.0
155,ST KILDA EAST,1382500.0,1677500.0,1460000.0,1620000.0,1560500.0,1650000.0,1840000.0,1785000.0,1667500.0,1690500.0
156,STAWELL,177000.0,177000.0,188000.0,190000.0,189000.0,227000.0,290000.0,355000.0,319000.0,315000.0
157,STRATHFIELDSAYE,408000.0,425000.0,455000.0,444000.0,476500.0,535000.0,632000.0,702500.0,717500.0,700000.0
158,STRATHMORE,997500.0,1140000.0,1230000.0,1357500.0,1310000.0,1360000.0,1570000.0,1605000.0,1416500.0,1612000.0
159,SUNBURY,370000.0,395000.0,492000.0,546000.0,533500.0,571000.0,645000.0,670000.0,660000.0,665000.0
160,SUNSHINE,530500.0,675000.0,765000.0,742000.0,720000.0,750000.0,870000.0,856500.0,800000.0,820000.0
161,SUNSHINE NORTH,495000.0,560000.0,653000.0,673500.0,647000.0,689500.0,710000.0,750000.0,724500.0,750000.0
162,SUNSHINE WEST,450000.0,520000.0,639000.0,635000.0,635000.0,657000.0,740000.0,750000.0,700000.0,685000.0
163,SWAN HILL,248000.0,262500.0,252000.0,267000.0,285000.0,319500.0,362000.0,405000.0,435000.0,472500.0
164,SYDENHAM,440000.0,505000.0,590000.0,615000.0,591500.0,635000.0,690000.0,697500.0,741500.0,704000.0
165,TAYLORS HILL,530000.0,600000.0,686000.0,723000.0,702000.0,754000.0,840000.0,908000.0,906500.0,885000.0
166,TAYLORS LAKES,561500.0,635000.0,720000.0,763500.0,750000.0,777500.0,883500.0,936000.0,922500.0,945000.0
167,TEMPLESTOWE,1180000.0,1260000.0,1415000.0,1308000.0,1292500.0,1381500.0,1603000.0,1628500.0,1695000.0,1650000.0
168,TEMPLESTOWE LOWER,1060000.0,1105500.0,1302000.0,1150000.0,1080000.0,1189000.0,1432500.0,1390000.0,1410000.0,1362000.0
169,THE BASIN,550000.0,595000.0,610000.0,682500.0,695000.0,739000.0,875000.0,864000.0,850000.0,881000.0
170,THOMASTOWN,437000.0,493000.0,654000.0,636000.0,592000.0,620000.0,720000.0,710000.0,691000.0,720000.0
171,THORNBURY,918000.0,1079500.0,1230000.0,1137500.0,1150000.0,1252500.0,1500000.0,1455000.0,1410000.0,1430000.0

Table 2: Suburbs with matching ABS population values (2015-2024)
(Named as requested: population density table)

,suburb,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,ABBOTSFORD,8078.0,8770.0,9291.0,9527.0,9594.0,9672.0,9258.0,9450.0,9948.0,10207.0
1,AIRPORT WEST,7694.0,7903.0,8019.0,8169.0,8390.0,8362.0,8240.0,8273.0,8437.0,8612.0
2,ALBERT PARK,16053.0,16490.0,16500.0,16728.0,17081.0,16955.0,16011.0,16126.0,16811.0,17094.0
3,ALBION,2908.0,2974.0,3328.0,3663.0,3929.0,4192.0,4371.0,4541.0,4702.0,4813.0
4,ALEXANDRA,6404.0,6474.0,6550.0,6646.0,6687.0,6690.0,6771.0,6785.0,6820.0,6836.0
5,ALFREDTON,11039.0,11852.0,12649.0,13537.0,14434.0,15507.0,16841.0,17988.0,18966.0,20082.0
6,ALTONA,12979.0,13206.0,13443.0,13657.0,13861.0,13878.0,13655.0,13711.0,13877.0,14190.0
7,ALTONA MEADOWS,19818.0,20106.0,20164.0,20101.0,20031.0,19500.0,18660.0,18334.0,18604.0,18733.0
8,ALTONA NORTH,14519.0,14787.0,14999.0,15185.0,15400.0,15396.0,15084.0,15034.0,15342.0,15851.0
9,ARARAT,8324.0,8386.0,8405.0,8428.0,8465.0,8552.0,8470.0,8375.0,8311.0,8288.0
10,ARMADALE,9485.0,9619.0,9635.0,9906.0,10044.0,10075.0,9433.0,9343.0,9735.0,9934.0
11,ASCOT VALE,15219.0,15497.0,15683.0,15752.0,15774.0,15784.0,15351.0,15148.0,15674.0,16078.0
12,AVOCA,3317.0,3323.0,3351.0,3393.0,3422.0,3447.0,3501.0,3527.0,3578.0,3614.0
13,AVONDALE HEIGHTS,12022.0,12199.0,12329.0,12451.0,12628.0,12642.0,12473.0,12377.0,12556.0,12792.0
14,BACCHUS MARSH,20207.0,20989.0,21776.0,22493.0,23360.0,24263.0,25057.0,25618.0,26033.0,26531.0
15,BAIRNSDALE,14524.0,14899.0,15170.0,15405.0,15547.0,15563.0,15653.0,15743.0,15769.0,15724.0
16,BALWYN,16573.0,16679.0,16920.0,17081.0,17156.0,17031.0,16323.0,16286.0,16698.0,16901.0
17,BALWYN NORTH,21332.0,21440.0,21618.0,21780.0,21935.0,21930.0,21406.0,21306.0,21866.0,22276.0
18,BANNOCKBURN,6192.0,6549.0,6881.0,7130.0,7362.0,7608.0,7738.0,7933.0,8114.0,8266.0
19,BAYSWATER,12415.0,12584.0,12696.0,12818.0,12948.0,12992.0,12708.0,12692.0,13011.0,13270.0
20,BAYSWATER NORTH,12126.0,12257.0,12316.0,12392.0,12423.0,12332.0,11967.0,11829.0,11901.0,12007.0
21,BEAUFORT,4317.0,4454.0,4486.0,4448.0,4543.0,4606.0,4621.0,4595.0,4686.0,4811.0
22,BEAUMARIS,13995.0,14250.0,14275.0,14434.0,14404.0,14362.0,14123.0,13999.0,14199.0,14376.0
23,BEECHWORTH,4541.0,4632.0,4735.0,4801.0,4872.0,4936.0,4953.0,4897.0,4915.0,4933.0
24,BELMONT,14175.0,14312.0,14599.0,14754.0,14975.0,15096.0,15000.0,14926.0,14962.0,15085.0
25,BENALLA,10425.0,10420.0,10484.0,10553.0,10620.0,10699.0,10753.0,10711.0,10755.0,10833.0
26,BENDIGO,14753.0,14770.0,14844.0,14941.0,15072.0,15087.0,14955.0,14706.0,14566.0,14422.0
27,BROADMEADOWS,13529.0,13916.0,14288.0,14555.0,14765.0,14747.0,14063.0,13921.0,14313.0,14734.0
28,BROOKFIELD,8648.0,9153.0,9505.0,9691.0,9787.0,9901.0,9948.0,9959.0,10137.0,10364.0
29,BRUNSWICK EAST,11062.0,11716.0,12154.0,12392.0,12602.0,13064.0,12964.0,13238.0,13691.0,14328.0
30,BRUNSWICK WEST,14344.0,14523.0,14556.0,14695.0,14854.0,15010.0,14497.0,14619.0,15115.0,15538.0
31,BULLEEN,11504.0,11565.0,11585.0,11631.0,11626.0,11657.0,11370.0,11419.0,11629.0,11730.0
32,BUNINYONG,7191.0,7311.0,7409.0,7418.0,7458.0,7377.0,7229.0,7232.0,7299.0,7320.0
33,BURNSIDE,4812.0,4943.0,5178.0,5400.0,5549.0,5743.0,5857.0,5995.0,6199.0,6418.0
34,BURNSIDE HEIGHTS,6265.0,6431.0,6546.0,6658.0,6741.0,6628.0,6440.0,6334.0,6473.0,6460.0
35,BURWOOD EAST,10713.0,10772.0,10840.0,10898.0,10974.0,11053.0,10774.0,11074.0,11862.0,12323.0
36,CAIRNLEA,10040.0,10206.0,10362.0,10444.0,10452.0,10510.0,10142.0,9989.0,10071.0,10009.0
37,CAMBERWELL,22179.0,22646.0,22799.0,22812.0,22839.0,22604.0,21500.0,21249.0,21785.0,22050.0
38,CAMPERDOWN,3516.0,3526.0,3545.0,3561.0,3540.0,3497.0,3471.0,3428.0,3379.0,3367.0
39,CARLTON,18983.0,20242.0,20651.0,20831.0,21029.0,20865.0,17064.0,17942.0,21321.0,23758.0
40,CARNEGIE,18645.0,19091.0,19288.0,19551.0,19686.0,19676.0,18791.0,18910.0,20056.0,20837.0
41,CAROLINE SPRINGS,20377.0,20968.0,21299.0,21404.0,21352.0,21238.0,20634.0,20659.0,20896.0,20954.0
42,CARRUM DOWNS,21291.0,21549.0,21823.0,22045.0,22195.0,22391.0,22264.0,22386.0,22858.0,23286.0
43,CASTLEMAINE,10545.0,10770.0,10888.0,11015.0,11146.0,11277.0,11291.0,11330.0,11475.0,11507.0
44,CHELSEA HEIGHTS,5485.0,5538.0,5556.0,5564.0,5586.0,5562.0,5426.0,5364.0,5359.0,5431.0
45,CHIRNSIDE PARK,9941.0,10266.0,10678.0,11046.0,11468.0,11767.0,11876.0,12079.0,12373.0,12483.0
46,CHURCHILL,11574.0,11594.0,11613.0,11642.0,11693.0,11781.0,11858.0,11968.0,12069.0,12189.0
47,CLAYTON SOUTH,13141.0,13296.0,13422.0,13662.0,14096.0,14152.0,13562.0,13923.0,14714.0,15085.0
48,CLIFTON SPRINGS,13074.0,13593.0,14150.0,14763.0,15580.0,16143.0,16729.0,17105.0,17494.0,17695.0
49,COBRAM,6399.0,6420.0,6445.0,6459.0,6457.0,6481.0,6440.0,6463.0,6621.0,6549.0
50,COBURG NORTH,7789.0,8112.0,8383.0,8589.0,8694.0,8775.0,8513.0,8581.0,8788.0,8882.0
51,COLAC,12337.0,12450.0,12553.0,12651.0,12719.0,12775.0,12698.0,12601.0,12602.0,12606.0
52,COLLINGWOOD,8582.0,9235.0,9444.0,9605.0,9829.0,9969.0,9351.0,9589.0,10398.0,11034.0
53,CRANBOURNE,20568.0,20888.0,21207.0,21414.0,21516.0,21673.0,21581.0,21578.0,21983.0,22468.0
54,CRANBOURNE WEST,13995.0,15685.0,17160.0,18628.0,19788.0,20867.0,21853.0,22935.0,23770.0,24843.0
55,CROYDON,11528.0,11516.0,11545.0,11571.0,11594.0,11456.0,11011.0,10958.0,11195.0,11318.0
56,CROYDON SOUTH,4824.0,4856.0,4901.0,4918.0,4949.0,5015.0,4936.0,4960.0,5026.0,5118.0
57,DANDENONG NORTH,23449.0,23684.0,23834.0,23930.0,23974.0,23655.0,22834.0,22542.0,22878.0,23248.0
58,DAYLESFORD,9018.0,9117.0,9243.0,9389.0,9548.0,9729.0,9874.0,9990.0,10069.0,10218.0
59,DEER PARK,18523.0,18850.0,19066.0,19291.0,19238.0,18976.0,18219.0,17960.0,18163.0,18398.0
60,DELACOMBE,6846.0,7195.0,7622.0,8183.0,8890.0,9755.0,10648.0,11769.0,12824.0,14218.0
61,DELAHEY,8815.0,8841.0,8796.0,8732.0,8663.0,8533.0,8148.0,8024.0,8000.0,7981.0
62,DERRIMUT,8223.0,8686.0,8962.0,9037.0,9114.0,9015.0,8748.0,8705.0,8826.0,8880.0
63,DIGGERS REST,2252.0,2447.0,2637.0,2989.0,3760.0,4651.0,5302.0,5829.0,6425.0,6946.0
64,DINGLEY VILLAGE,10603.0,10611.0,10651.0,10700.0,10766.0,10736.0,10553.0,10542.0,10654.0,10728.0
65,DONCASTER,21076.0,21885.0,22707.0,23236.0,24172.0,25118.0,25173.0,25632.0,26863.0,27827.0
66,DOVETON,11665.0,11867.0,12095.0,12260.0,12345.0,12513.0,12058.0,12134.0,12468.0,12728.0
67,DROMANA,10785.0,11454.0,12015.0,12473.0,12778.0,13175.0,13469.0,13560.0,13560.0,13756.0
68,DROUIN,15787.0,16435.0,17117.0,17780.0,18447.0,19198.0,19800.0,20528.0,21152.0,21760.0
69,FLEMINGTON,10531.0,10734.0,10666.0,10654.0,10460.0,10270.0,9181.0,9143.0,9729.0,10215.0
70,FLINDERS,5604.0,5642.0,5720.0,5798.0,5878.0,5957.0,6024.0,6026.0,5989.0,6030.0
71,FOOTSCRAY,16762.0,17343.0,17673.0,17905.0,18054.0,18092.0,17419.0,18017.0,19845.0,20607.0
72,FOREST HILL,10874.0,11074.0,11197.0,11260.0,11204.0,11166.0,10866.0,10853.0,11008.0,11179.0
73,FOSTER,8774.0,8897.0,8973.0,9028.0,9124.0,9290.0,9378.0,9421.0,9479.0,9574.0
74,FRANKSTON,23135.0,23510.0,23738.0,23992.0,24129.0,24264.0,23909.0,23809.0,24132.0,24736.0
75,FRANKSTON NORTH,19827.0,19939.0,19999.0,20022.0,20010.0,19973.0,19666.0,19587.0,19730.0,19791.0
76,FRANKSTON SOUTH,18793.0,18995.0,19104.0,19194.0,19260.0,19182.0,18948.0,18985.0,19139.0,19184.0
77,GEELONG,12955.0,13077.0,13207.0,13337.0,13439.0,13498.0,13487.0,13521.0,13623.0,13690.0
78,GISBORNE,12850.0,13312.0,13611.0,13909.0,14121.0,14245.0,14340.0,14446.0,14885.0,15405.0
79,GOWANBRAE,2999.0,3042.0,3092.0,3120.0,3139.0,3156.0,3141.0,3123.0,3174.0,3173.0
80,GREENSBOROUGH,21224.0,21348.0,21413.0,21460.0,21476.0,21373.0,20995.0,20830.0,20939.0,21287.0
81,HADFIELD,5803.0,5911.0,6021.0,6110.0,6273.0,6394.0,6298.0,6364.0,6502.0,6625.0
82,HALLAM,11125.0,11335.0,11516.0,11697.0,11911.0,11968.0,11598.0,11554.0,11737.0,11898.0
83,HAMPTON,18345.0,18611.0,18735.0,18819.0,18912.0,18997.0,18405.0,18477.0,18793.0,19142.0
84,HAWTHORN EAST,15601.0,16192.0,16470.0,16676.0,16756.0,16698.0,15881.0,16063.0,16838.0,17242.0
85,HEATHCOTE,4452.0,4529.0,4608.0,4695.0,4790.0,4902.0,5026.0,5148.0,5247.0,5311.0
86,HEIDELBERG WEST,14634.0,14806.0,15054.0,15202.0,15544.0,15540.0,15039.0,15244.0,15799.0,16641.0
87,HIGHTON,22390.0,22794.0,23074.0,23463.0,23807.0,23858.0,24091.0,24561.0,25098.0,25546.0
88,KEILOR,8886.0,8993.0,9013.0,9012.0,8953.0,8778.0,8596.0,8531.0,8548.0,8675.0
89,KEILOR DOWNS,13960.0,13943.0,13920.0,13870.0,13765.0,13567.0,13193.0,12974.0,12995.0,13036.0
90,KEILOR EAST,14938.0,15200.0,15263.0,15357.0,15475.0,15471.0,15174.0,15173.0,15289.0,15463.0
91,KERANG,3900.0,3898.0,3900.0,3915.0,3924.0,3946.0,3944.0,3883.0,3835.0,3806.0
92,KIALLA,7213.0,7407.0,7703.0,8064.0,8454.0,8758.0,9067.0,9445.0,9691.0,10058.0
93,KILSYTH,9280.0,9470.0,9595.0,9685.0,9879.0,9962.0,9980.0,10087.0,10326.0,10647.0
94,KINGLAKE,3922.0,3984.0,4049.0,4121.0,4153.0,4172.0,4237.0,4291.0,4329.0,4369.0
95,KINGSBURY,11730.0,11965.0,12095.0,12071.0,11792.0,11525.0,10549.0,10747.0,11680.0,12454.0
96,KOO WEE RUP,7440.0,7719.0,8044.0,8303.0,8757.0,9387.0,10160.0,10802.0,11503.0,11981.0
97,KORUMBURRA,9167.0,9253.0,9347.0,9451.0,9593.0,9758.0,9787.0,9902.0,9872.0,9944.0
98,KYABRAM,11001.0,11034.0,11067.0,11055.0,11096.0,11134.0,11057.0,10975.0,10917.0,10836.0
99,KYNETON,9656.0,9782.0,9923.0,10070.0,10219.0,10371.0,10499.0,10549.0,10554.0,10580.0
100,LAKES ENTRANCE,9949.0,10038.0,10213.0,10424.0,10647.0,10873.0,11095.0,11163.0,11221.0,11259.0
101,LANGWARRIN,24357.0,24694.0,24863.0,25019.0,25109.0,25259.0,25252.0,25337.0,25531.0,25697.0
102,LARA,17996.0,18587.0,19152.0,19778.0,20283.0,20575.0,20859.0,21342.0,22051.0,22923.0
103,LAVERTON,8334.0,9385.0,10255.0,10899.0,11499.0,11972.0,11643.0,11839.0,12359.0,12672.0
104,LEONGATHA,11077.0,11202.0,11236.0,11328.0,11416.0,11437.0,11439.0,11545.0,11617.0,11636.0
105,LEOPOLD,12544.0,13140.0,13359.0,13411.0,13319.0,13279.0,13220.0,13314.0,13489.0,13715.0
106,LYSTERFIELD,6898.0,6917.0,6919.0,6919.0,6890.0,6802.0,6654.0,6552.0,6552.0,6583.0
107,MACEDON,3476.0,3525.0,3537.0,3542.0,3541.0,3536.0,3540.0,3571.0,3570.0,3623.0
108,MAFFRA,13873.0,13973.0,14132.0,14257.0,14418.0,14598.0,14698.0,14913.0,15138.0,15388.0
109,MAIDEN GULLY,4983.0,5155.0,5250.0,5322.0,5364.0,5465.0,5502.0,5587.0,5716.0,5801.0
110,MALVERN EAST,22174.0,22575.0,22785.0,22983.0,23099.0,23079.0,22202.0,22376.0,23133.0,23656.0
111,MARIBYRNONG,12562.0,12950.0,13161.0,13204.0,13241.0,13263.0,12712.0,12867.0,13364.0,13751.0
112,MEADOW HEIGHTS,15755.0,15779.0,15847.0,15876.0,15868.0,15840.0,15070.0,14627.0,14853.0,14915.0
113,MELTON,8183.0,8281.0,8319.0,8338.0,8359.0,8261.0,7966.0,7893.0,7990.0,8017.0
114,MELTON WEST,17387.0,18157.0,19045.0,20034.0,20993.0,21432.0,21505.0,21807.0,22199.0,22617.0
115,MENTONE,13332.0,13695.0,13784.0,13813.0,13883.0,13856.0,13303.0,13347.0,13702.0,13945.0
116,MERBEIN,4767.0,4820.0,4900.0,4963.0,4989.0,5002.0,4954.0,4898.0,4900.0,4916.0
117,MURRUMBEENA,9640.0,9809.0,9894.0,9897.0,9878.0,9771.0,9467.0,9526.0,9760.0,10010.0
118,MYRTLEFORD,4689.0,4742.0,4738.0,4734.0,4736.0,4734.0,4717.0,4671.0,4637.0,4606.0
119,NAGAMBIE,3936.0,4048.0,4106.0,4190.0,4251.0,4388.0,4509.0,4619.0,4693.0,4811.0
120,NARRE WARREN NORTH,7909.0,8183.0,8279.0,8372.0,8383.0,8365.0,8308.0,8225.0,8191.0,8160.0
121,NEWPORT,18134.0,18523.0,18726.0,18975.0,19261.0,19414.0,18983.0,18928.0,19445.0,19879.0
122,NOBLE PARK NORTH,7826.0,7871.0,7874.0,7858.0,7828.0,7762.0,7518.0,7450.0,7573.0,7622.0
123,NORLANE,8857.0,8931.0,8996.0,9023.0,9060.0,9070.0,9040.0,8937.0,8931.0,8906.0
124,NORTH MELBOURNE,15556.0,16464.0,17002.0,17585.0,17941.0,18154.0,15945.0,16510.0,17942.0,19069.0
125,NUMURKAH,12420.0,12422.0,12447.0,12473.0,12497.0,12524.0,12502.0,12484.0,12430.0,12438.0
126,NUNAWADING,12089.0,12363.0,12628.0,12786.0,12840.0,12861.0,12518.0,12576.0,12903.0,13192.0
127,OAK PARK,7366.0,7604.0,7781.0,7943.0,8073.0,8153.0,7978.0,8081.0,8257.0,8450.0
128,OCEAN GROVE,15547.0,16186.0,16814.0,17430.0,18117.0,18766.0,19393.0,19828.0,20188.0,20456.0
129,ORBOST,6528.0,6497.0,6507.0,6533.0,6570.0,6619.0,6693.0,6668.0,6651.0,6671.0
130,PASCOE VALE,16547.0,17225.0,17551.0,17860.0,17962.0,17951.0,17402.0,17425.0,17876.0,18356.0
131,PASCOE VALE SOUTH,10251.0,10465.0,10698.0,10834.0,10873.0,10836.0,10463.0,10398.0,10600.0,10831.0
132,PAYNESVILLE,6200.0,6374.0,6455.0,6599.0,6740.0,6796.0,6902.0,6971.0,7020.0,7113.0
133,PORT MELBOURNE,17254.0,17469.0,17494.0,17354.0,17310.0,16998.0,16366.0,16365.0,16752.0,16817.0
134,PORTARLINGTON,7276.0,7517.0,7775.0,8092.0,8417.0,8886.0,9460.0,9911.0,10260.0,10599.0
135,PORTLAND,10919.0,10943.0,10997.0,11067.0,11150.0,11198.0,11183.0,11135.0,11124.0,11116.0
136,RED CLIFFS,5855.0,5947.0,6054.0,6121.0,6158.0,6210.0,6123.0,6070.0,6023.0,6043.0
137,RIDDELLS CREEK,4113.0,4174.0,4250.0,4298.0,4340.0,4442.0,4498.0,4521.0,4537.0,4520.0
138,RINGWOOD,17654.0,17931.0,18301.0,18504.0,18876.0,19158.0,18919.0,18962.0,19297.0,19593.0
139,RINGWOOD EAST,20657.0,21031.0,21322.0,21495.0,21660.0,21785.0,21351.0,21244.0,21435.0,21824.0
140,RINGWOOD NORTH,9910.0,9991.0,10056.0,10073.0,10044.0,9931.0,9723.0,9651.0,9683.0,9777.0
141,ROBINVALE,3412.0,3382.0,3484.0,3598.0,3702.0,3769.0,3749.0,3664.0,3718.0,3691.0
142,ROCHESTER,3887.0,3895.0,3923.0,3941.0,3949.0,3973.0,3988.0,3943.0,3769.0,3683.0
143,ROMSEY,9389.0,9663.0,9898.0,10102.0,10372.0,10612.0,10835.0,11079.0,11247.0,11463.0
144,ROSEDALE,4759.0,4791.0,4856.0,4900.0,4920.0,4870.0,4912.0,4853.0,4865.0,4893.0
145,RUSHWORTH,4084.0,4076.0,4070.0,4079.0,4094.0,4129.0,4168.0,4144.0,4165.0,4179.0
146,RUTHERGLEN,3857.0,3907.0,3934.0,3976.0,4012.0,4029.0,4021.0,4024.0,4075.0,4108.0
147,SALE,14781.0,14891.0,14914.0,14988.0,15075.0,15173.0,15264.0,15258.0,15275.0,15270.0
148,SEABROOK,5352.0,5408.0,5417.0,5397.0,5368.0,5250.0,4999.0,4854.0,4903.0,4932.0
149,SEYMOUR,6407.0,6403.0,6433.0,6477.0,6516.0,6538.0,6546.0,6557.0,6637.0,6816.0
150,SOMERVILLE,18685.0,18878.0,18906.0,18911.0,18847.0,18795.0,18693.0,18596.0,18776.0,18921.0
151,SOUTH MELBOURNE,12177.0,12407.0,12512.0,12716.0,12764.0,12721.0,11856.0,11828.0,12455.0,12826.0
152,SPRINGVALE,22188.0,22761.0,23216.0,23549.0,23774.0,23650.0,22515.0,22598.0,23468.0,24023.0
153,SPRINGVALE SOUTH,13065.0,13227.0,13299.0,13327.0,13338.0,13295.0,12728.0,12450.0,12813.0,13111.0
154,ST ARNAUD,3413.0,3353.0,3352.0,3364.0,3394.0,3427.0,3428.0,3436.0,3416.0,3384.0
155,ST KILDA EAST,17315.0,17613.0,17568.0,17655.0,17715.0,17259.0,16073.0,15951.0,16707.0,17237.0
156,STAWELL,8239.0,8225.0,8249.0,8279.0,8322.0,8387.0,8467.0,8422.0,8435.0,8369.0
157,STRATHFIELDSAYE,8355.0,8775.0,9125.0,9483.0,9901.0,10312.0,10679.0,11012.0,11248.0,11457.0
158,STRATHMORE,9729.0,9968.0,10157.0,10269.0,10311.0,10277.0,10107.0,10167.0,10301.0,10427.0
159,SUNBURY,13170.0,13238.0,13338.0,13454.0,13637.0,13858.0,13788.0,13820.0,14197.0,14758.0
160,SUNSHINE,10083.0,10241.0,10303.0,10318.0,10306.0,10100.0,9568.0,9601.0,9910.0,10059.0
161,SUNSHINE NORTH,11890.0,12123.0,12323.0,12461.0,12490.0,12451.0,12161.0,11966.0,12185.0,12462.0
162,SUNSHINE WEST,19013.0,19533.0,19786.0,19893.0,19915.0,19633.0,18770.0,18266.0,18527.0,18724.0
163,SWAN HILL,11022.0,11079.0,11153.0,11216.0,11264.0,11278.0,11173.0,11003.0,10905.0,10781.0
164,SYDENHAM,12432.0,12585.0,12662.0,12679.0,12660.0,12432.0,11859.0,11583.0,11776.0,11929.0
165,TAYLORS HILL,19486.0,20218.0,20443.0,20453.0,20444.0,20288.0,19794.0,19859.0,19863.0,19818.0
166,TAYLORS LAKES,18474.0,18455.0,18313.0,18175.0,17974.0,17614.0,17070.0,16754.0,16903.0,16966.0
167,TEMPLESTOWE,17550.0,17682.0,17713.0,17680.0,17674.0,17548.0,17101.0,17136.0,17429.0,17419.0
168,TEMPLESTOWE LOWER,14155.0,14305.0,14403.0,14419.0,14441.0,14581.0,14280.0,14336.0,14433.0,14586.0
169,THE BASIN,4423.0,4441.0,4460.0,4469.0,4455.0,4415.0,4380.0,4299.0,4297.0,4318.0
170,THOMASTOWN,21442.0,21485.0,21490.0,21458.0,21367.0,21173.0,20201.0,19959.0,20162.0,20484.0
171,THORNBURY,19254.0,19578.0,19720.0,19714.0,19729.0,19791.0,19153.0,19126.0,19544.0,19893.0

**Classification: Status-based treated/untreated groups (from Daniel Bowen's November 2022 update)**

Suburbs are classified based on their status in the level crossing removal program:
- Treated (1.0): Status is "Completed", "Planning", or "Underway"
- Untreated (0.0): Status is blank or not listed

In [4]:
from pathlib import Path
import re
from io import StringIO
import pandas as pd
import requests

project_root = Path.cwd()
if not (project_root / "data").exists():
    project_root = project_root.parent

# Daniel Bowen source page (Nov 2022 update)
url = "https://danielbowen.com/2022/11/05/level-crossings-nov-2022-update/"

# Use a browser-like User-Agent to avoid 403 responses from default urllib headers.
headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    )
}
response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()
tables = pd.read_html(StringIO(response.text))

def normalize_col_name(col: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", str(col).strip().lower())

def pick_suburb_status_table(html_tables: list[pd.DataFrame]) -> tuple[pd.DataFrame, str, str]:
    candidates = []
    for t in html_tables:
        df = t.copy()

        # Flatten MultiIndex columns if present.
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = [" ".join([str(c) for c in col if str(c) != "nan"]).strip() for col in df.columns]

        col_map = {c: normalize_col_name(c) for c in df.columns}
        suburb_col = None
        status_col = None

        for original, normalized in col_map.items():
            if normalized in {"suburb", "suburbs"}:
                suburb_col = original
            if normalized == "status112022":
                status_col = original

        if suburb_col is not None and status_col is not None:
            candidates.append((df, suburb_col, status_col))

    if not candidates:
        raise ValueError("Could not find table with both suburb/suburbs and status 11/2022 columns.")

    # Use the largest matching table as the main dataset.
    return max(candidates, key=lambda item: len(item[0]))

df_raw, suburb_col, status_col = pick_suburb_status_table(tables)

# Extract data ONLY from the suburb/suburbs and status columns.
df_bowen = df_raw[[suburb_col, status_col]].copy()
df_bowen.columns = ["suburb", "status"]

# Clean text and remove blank suburbs.
df_bowen["suburb"] = df_bowen["suburb"].fillna("").astype(str).str.strip().str.lower()
df_bowen["status"] = df_bowen["status"].fillna("").astype(str).str.strip().str.lower()
df_bowen = df_bowen[df_bowen["suburb"].ne("")].copy()

# Resolve duplicates by keeping the strongest status for each suburb.
status_priority = {"completed": 4, "underway": 3, "planning": 2, "": 1}
df_bowen["priority"] = df_bowen["status"].map(lambda s: status_priority.get(s, 1))

df_bowen_suburb = (
    df_bowen.sort_values("priority", ascending=False)
            .drop_duplicates(subset=["suburb"], keep="first")
            .loc[:, ["suburb", "status"]]
            .sort_values("suburb")
            .reset_index(drop=True)
)

# Treated definition from Daniel Bowen status table.
treated_statuses = {"completed", "planning", "underway"}
df_bowen_suburb["treated"] = df_bowen_suburb["status"].apply(
    lambda s: 1.0 if s in treated_statuses else 0.0
)

treated_bowen = df_bowen_suburb[df_bowen_suburb["treated"] == 1.0].reset_index(drop=True)
untreated_bowen = df_bowen_suburb[df_bowen_suburb["treated"] == 0.0].reset_index(drop=True)

clean_dir = project_root / "data" / "clean"
clean_dir.mkdir(parents=True, exist_ok=True)
treated_output = clean_dir / "daniel_bowen_treated_suburbs_2022.csv"
untreated_output = clean_dir / "daniel_bowen_untreated_suburbs_2022.csv"

treated_bowen.to_csv(treated_output, index=False)
untreated_bowen.to_csv(untreated_output, index=False)

print("Daniel Bowen — classification using Suburb/Suburbs + Status 11/2022 only")
print(f"Total unique suburbs from the page: {len(df_bowen_suburb)}")
print(f"Treated (completed/planning/underway): {len(treated_bowen)}")
print(f"Untreated (other/blank): {len(untreated_bowen)}")
print("\nTREATED suburbs (treated = 1.0):")
display(treated_bowen)
print(f"Saved treated table to: {treated_output}")
print("\nUNTREATED suburbs (treated = 0.0):")
display(untreated_bowen)
print(f"Saved untreated table to: {untreated_output}")

Daniel Bowen — classification using Suburb/Suburbs + Status 11/2022 only
Total unique suburbs from the page: 179
Treated (completed/planning/underway): 86
Untreated (other/blank): 93

TREATED suburbs (treated = 1.0):

          suburb     status  treated
0     alphington  completed      1.0
1         altona  completed      1.0
2         ardeer   underway      1.0
3      aspendale   planning      1.0
4      bayswater  completed      1.0
..           ...        ...      ...
81       wallace  completed      1.0
82      werribee  completed      1.0
83  williamstown  completed      1.0
84       wodonga  completed      1.0
85    yarraville   planning      1.0

[86 rows x 3 columns]

Saved treated table to: c:\Users\samantha\Desktop\uni ૮₍•᷄ ࡇ•᷅₎ა\Y3S1\ECC3479\ECC3479-project\ecc3479-project\ECC3479-project (data + GitHub repo)\data\clean\daniel_bowen_treated_suburbs_2022.csv

UNTREATED suburbs (treated = 0.0):

           suburb status  treated
0          ararat             0.0
1          avenel             0.0
2   bacchus marsh             0.0
3        ballarat             0.0
4          baxter             0.0
..            ...    ...      ...
88      wendouree             0.0
89       westmere             0.0
90        windsor             0.0
91        woodend             0.0
92       yarragon             0.0

[93 rows x 3 columns]

Saved untreated table to: c:\Users\samantha\Desktop\uni ૮₍•᷄ ࡇ•᷅₎ა\Y3S1\ECC3479\ECC3479-project\ecc3479-project\ECC3479-project (data + GitHub repo)\data\clean\daniel_bowen_untreated_suburbs_2022.csv