# ECC3479 notebook

# Population density

## Sunshine's population density

In [ ]:
import pandas as pd


file_path = r"C:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\raw\abs_population.xlsx"


header_rows = pd.read_excel(file_path, sheet_name="Table 1", header=None, nrows=6)
column_names = header_rows.iloc[5, :10].tolist() + header_rows.iloc[4, 10:].tolist()

df = pd.read_excel(file_path, sheet_name="Table 1", header=None, skiprows=6)
df.columns = column_names

sunshine_df = df[df["SA2 name"] == "Sunshine"].copy()
if sunshine_df.empty:
    raise ValueError("Sunshine row not found in the data.")

year_cols = [col for col in column_names if isinstance(col, (int, float)) and 2001 <= int(col) <= 2025]

sunshine_df[year_cols] = sunshine_df[year_cols].apply(pd.to_numeric, errors="coerce")

sunshine_long = sunshine_df.melt(
    id_vars="SA2 name",
    value_vars=year_cols,
    var_name="Year",
    value_name="Population"
)

sunshine_long["Year"] = sunshine_long["Year"].astype(int)

sunshine_long = sunshine_long[
    (sunshine_long["Year"] >= 2018) & (sunshine_long["Year"] <= 2025)
].copy()

area = 7.3
sunshine_long["Area_km2"] = area
sunshine_long["Density"] = sunshine_long["Population"] / area

target_path = r"C:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\sunshine_density.csv"
sunshine_long.to_csv(target_path, index=False)
print(f"Saved Sunshine density table to {target_path}")
print(sunshine_long)

Saved Sunshine density table to C:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\sunshine_density.csv
    SA2 name  Year  Population  Area_km2      Density
17  Sunshine  2018     10318.0       7.3  1413.424658
18  Sunshine  2019     10306.0       7.3  1411.780822
19  Sunshine  2020     10100.0       7.3  1383.561644
20  Sunshine  2021      9568.0       7.3  1310.684932
21  Sunshine  2022      9601.0       7.3  1315.205479
22  Sunshine  2023      9910.0       7.3  1357.534247
23  Sunshine  2024     10059.0       7.3  1377.945205
24  Sunshine  2025     10151.0       7.3  1390.547945

## Bundoora's population density

In [2]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd()
if not (project_root / "data" / "raw").exists():
    project_root = project_root.parent
input_path = project_root / "data" / "raw" / "abs_population.xlsx"
output_dir = project_root / "data" / "clean"
output_dir.mkdir(parents=True, exist_ok=True)

header_rows = pd.read_excel(input_path, sheet_name="Table 1", header=None, nrows=6)
column_names = header_rows.iloc[5, :10].tolist() + header_rows.iloc[4, 10:].tolist()

df = pd.read_excel(input_path, sheet_name="Table 1", header=None, skiprows=6)
df.columns = column_names

year_cols = [col for col in column_names if isinstance(col, (int, float)) and 2001 <= int(col) <= 2025]

suburb_name = "Bundoora - East"
area_km2 = 15.0

suburb_df = df[df["SA2 name"] == suburb_name].copy()
if suburb_df.empty:
    raise ValueError(f"{suburb_name} row not found")

suburb_df[year_cols] = suburb_df[year_cols].apply(pd.to_numeric, errors="coerce")

suburb_long = suburb_df.melt(
    id_vars="SA2 name",
    value_vars=year_cols,
    var_name="Year",
    value_name="Population"
)

suburb_long["Year"] = suburb_long["Year"].astype(int)
suburb_long = suburb_long[
    (suburb_long["Year"] >= 2018) & (suburb_long["Year"] <= 2025)
].copy()
suburb_long["Area_km2"] = area_km2
suburb_long["Density"] = suburb_long["Population"] / area_km2

output_path = output_dir / "bundoora-east_density.csv"
suburb_long.to_csv(output_path, index=False)

print("Bundoora - East population density (2018-2025)")
print(f"Land area: {area_km2} kmÂ²")
print(f"Saved table to: {output_path}")
print(suburb_long)

Bundoora - East population density (2018-2025)
Land area: 15.0 kmÂ²
Saved table to: c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\bundoora-east_density.csv
           SA2 name  Year  Population  Area_km2     Density
17  Bundoora - East  2018     10359.0      15.0  690.600000
18  Bundoora - East  2019     10372.0      15.0  691.466667
19  Bundoora - East  2020     10295.0      15.0  686.333333
20  Bundoora - East  2021      9920.0      15.0  661.333333
21  Bundoora - East  2022      9814.0      15.0  654.266667
22  Bundoora - East  2023      9993.0      15.0  666.200000
23  Bundoora - East  2024     10196.0      15.0  679.733333
24  Bundoora - East  2025     10339.0      15.0  689.266667

## Brunswick's population density

In [3]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd()
if not (project_root / "data" / "raw").exists():
    project_root = project_root.parent

input_path = project_root / "data" / "raw" / "abs_population.xlsx"
output_dir = project_root / "data" / "clean"
output_dir.mkdir(parents=True, exist_ok=True)

header_rows = pd.read_excel(input_path, sheet_name="Table 1", header=None, nrows=6)
column_names = header_rows.iloc[5, :10].tolist() + header_rows.iloc[4, 10:].tolist()

df = pd.read_excel(input_path, sheet_name="Table 1", header=None, skiprows=6)
df.columns = column_names

year_cols = [
    col for col in column_names
    if isinstance(col, (int, float)) and 2001 <= int(col) <= 2025
]

suburb_name = "Brunswick East"
area_km2 = 5.2

suburb_df = df[df["SA2 name"] == suburb_name].copy()
if suburb_df.empty:
    raise ValueError(f"{suburb_name} row not found")

suburb_df[year_cols] = suburb_df[year_cols].apply(pd.to_numeric, errors="coerce")

suburb_long = suburb_df.melt(
    id_vars="SA2 name",
    value_vars=year_cols,
    var_name="Year",
    value_name="Population"
)

suburb_long["Year"] = suburb_long["Year"].astype(int)
suburb_long = suburb_long[
    (suburb_long["Year"] >= 2018) & (suburb_long["Year"] <= 2025)
].copy()

suburb_long["Area_km2"] = area_km2
suburb_long["Density"] = suburb_long["Population"] / area_km2

output_path = output_dir / "brunswick-east_density.csv"
suburb_long.to_csv(output_path, index=False)

print("Brunswick East population density (2018-2025)")
print(f"Land area: {area_km2} kmÂ²")
print(f"Saved table to: {output_path}")
print(suburb_long)

Brunswick East population density (2018-2025)
Land area: 5.2 kmÂ²
Saved table to: c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\brunswick-east_density.csv
          SA2 name  Year  Population  Area_km2      Density
17  Brunswick East  2018     12392.0       5.2  2383.076923
18  Brunswick East  2019     12602.0       5.2  2423.461538
19  Brunswick East  2020     13064.0       5.2  2512.307692
20  Brunswick East  2021     12964.0       5.2  2493.076923
21  Brunswick East  2022     13238.0       5.2  2545.769231
22  Brunswick East  2023     13691.0       5.2  2632.884615
23  Brunswick East  2024     14328.0       5.2  2755.384615
24  Brunswick East  2025     14693.0       5.2  2825.576923

## Coburg's population density

In [ ]:
import pandas as pd
from pathlib import Path

project_root = Path.cwd()
if not (project_root / "data" / "raw").exists():
    project_root = project_root.parent

input_path = project_root / "data" / "raw" / "abs_population.xlsx"
output_dir = project_root / "data" / "clean"
output_dir.mkdir(parents=True, exist_ok=True)

header_rows = pd.read_excel(input_path, sheet_name="Table 1", header=None, nrows=6)
column_names = header_rows.iloc[5, :10].tolist() + header_rows.iloc[4, 10:].tolist()

df = pd.read_excel(input_path, sheet_name="Table 1", header=None, skiprows=6)
df.columns = column_names

year_cols = [
    col for col in column_names
    if isinstance(col, (int, float)) and 2001 <= int(col) <= 2025
]

suburb_name = "Coburg - East"
area_km2 = 7.0

suburb_df = df[df["SA2 name"] == suburb_name].copy()
if suburb_df.empty:
    raise ValueError(f"{suburb_name} row not found")

suburb_df[year_cols] = suburb_df[year_cols].apply(pd.to_numeric, errors="coerce")

suburb_long = suburb_df.melt(
    id_vars="SA2 name",
    value_vars=year_cols,
    var_name="Year",
    value_name="Population"
)

suburb_long["Year"] = suburb_long["Year"].astype(int)
suburb_long = suburb_long[
    (suburb_long["Year"] >= 2018) & (suburb_long["Year"] <= 2025)
].copy()

suburb_long["Area_km2"] = area_km2
suburb_long["Density"] = suburb_long["Population"] / area_km2

output_path = output_dir / "coburg-east_density.csv"
suburb_long.to_csv(output_path, index=False)

print("Coburg - East population density (2018-2025)")
print(f"Land area: {area_km2} kmÂ²")
print(f"Saved table to: {output_path}")
print(suburb_long)

Coburg - East population density (2018-2025)
Land area: 7.0 kmÂ²
Saved table to: c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\coburg-east_density.csv
         SA2 name  Year  Population  Area_km2      Density
17  Coburg - East  2018     13379.0       7.0  1911.285714
18  Coburg - East  2019     13397.0       7.0  1913.857143
19  Coburg - East  2020     13265.0       7.0  1895.000000
20  Coburg - East  2021     12675.0       7.0  1810.714286
21  Coburg - East  2022     12901.0       7.0  1843.000000
22  Coburg - East  2023     13482.0       7.0  1926.000000
23  Coburg - East  2024     13887.0       7.0  1983.857143
24  Coburg - East  2025     14457.0       7.0  2065.285714

## Combined population density for all suburbs

In [ ]:

import pandas as pd
from pathlib import Path

project_root = Path.cwd()
if not (project_root / "data" / "raw").exists():
    project_root = project_root.parent

input_path = project_root / "data" / "raw" / "abs_population.xlsx"
output_dir = project_root / "data" / "clean"
output_dir.mkdir(parents=True, exist_ok=True)

header_rows = pd.read_excel(input_path, sheet_name="Table 1", header=None, nrows=6)
column_names = header_rows.iloc[5, :10].tolist() + header_rows.iloc[4, 10:].tolist()

df = pd.read_excel(input_path, sheet_name="Table 1", header=None, skiprows=6)
df.columns = column_names

year_cols = [
    col for col in column_names
    if isinstance(col, (int, float)) and 2001 <= int(col) <= 2025
]

area_km2 = {
    "Sunshine": 7.3,
    "Bundoora - East": 15.0,
    "Coburg - East": 7.0,
    "Brunswick East": 5.2,
}

def normalize_file_name(name: str) -> str:
    return (
        name.lower()
        .replace(" - ", "-")
        .replace(" ", "-")
        .replace("/", "-")
        .replace("--", "-")
    )

def build_density_table(suburb_name: str, area_val: float):
    suburb_df = df[df["SA2 name"] == suburb_name].copy()
    if suburb_df.empty:
        raise ValueError(f"Suburb row not found: {suburb_name}")

    suburb_df[year_cols] = suburb_df[year_cols].apply(pd.to_numeric, errors="coerce")

    suburb_long = suburb_df.melt(
        id_vars="SA2 name",
        value_vars=year_cols,
        var_name="Year",
        value_name="Population"
    )

    suburb_long["Year"] = suburb_long["Year"].astype(int)
    suburb_long = suburb_long[
        (suburb_long["Year"] >= 2018) & (suburb_long["Year"] <= 2025)
    ].copy()

    suburb_long["Area_km2"] = area_val
    suburb_long["Density"] = suburb_long["Population"] / area_val
    suburb_long["Suburb"] = suburb_name

    return suburb_long[["Suburb", "Year", "Population", "Area_km2", "Density"]]

suburbs = ["Sunshine", "Bundoora - East", "Coburg - East", "Brunswick East"]

all_tables = []
for suburb in suburbs:
    table = build_density_table(suburb, area_km2[suburb])
    all_tables.append(table)

    output_path = output_dir / f"{normalize_file_name(suburb)}_density.csv"
    table.to_csv(output_path, index=False)
    print(f"Saved {suburb} density table to {output_path}")

combined_table = pd.concat(all_tables, ignore_index=True)
combined_output_path = output_dir / "all_suburbs_density.csv"
combined_table.to_csv(combined_output_path, index=False)

print(f"\nSaved combined density table to {combined_output_path}")
print(combined_table)

Saved Sunshine density table to c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\sunshine_density.csv
Saved Bundoora - East density table to c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\bundoora-east_density.csv
Saved Coburg - East density table to c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\coburg-east_density.csv
Saved Brunswick East density table to c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\brunswick-east_density.csv

Saved combined density table to c:\Users\ashit\OneDrive\Desktop\Y3S2\ECC 3479 - Data and Evidence in Economics\ECC3479 - Data Analysis Project\data\clean\all_suburbs_density.csv
             Suburb  Year  Population  Area_km2      Density
0          Sunshine  2018     10318.0       7.3  1413.424658
1          Sunshine  2019     10306.0       7.3  1411.780822
2          Sunshine  2020     10100.0       7.3  1383.561644
3          Sunshine  2021      9568.0       7.3  1310.684932
4          Sunshine  2022      9601.0       7.3  1315.205479
5          Sunshine  2023      9910.0       7.3  1357.534247
6          Sunshine  2024     10059.0       7.3  1377.945205
7          Sunshine  2025     10151.0       7.3  1390.547945
8   Bundoora - East  2018     10359.0      15.0   690.600000
9   Bundoora - East  2019     10372.0      15.0   691.466667
10  Bundoora - East  2020     10295.0      15.0   686.333333
11  Bundoora - East  2021      9920.0      15.0   661.333333
12  Bundoora - East  2022      9814.0      15.0   654.266667
13  Bundoora - East  2023      9993.0      15.0   666.200000
14  Bundoora - East  2024     10196.0      15.0   679.733333
15  Bundoora - East  2025     10339.0      15.0   689.266667
16    Coburg - East  2018     13379.0       7.0  1911.285714
17    Coburg - East  2019     13397.0       7.0  1913.857143
18    Coburg - East  2020     13265.0       7.0  1895.000000
19    Coburg - East  2021     12675.0       7.0  1810.714286
20    Coburg - East  2022     12901.0       7.0  1843.000000
21    Coburg - East  2023     13482.0       7.0  1926.000000
22    Coburg - East  2024     13887.0       7.0  1983.857143
23    Coburg - East  2025     14457.0       7.0  2065.285714
24   Brunswick East  2018     12392.0       5.2  2383.076923
25   Brunswick East  2019     12602.0       5.2  2423.461538
26   Brunswick East  2020     13064.0       5.2  2512.307692
27   Brunswick East  2021     12964.0       5.2  2493.076923
28   Brunswick East  2022     13238.0       5.2  2545.769231
29   Brunswick East  2023     13691.0       5.2  2632.884615
30   Brunswick East  2024     14328.0       5.2  2755.384615
31   Brunswick East  2025     14693.0       5.2  2825.576923

# Household average income/year in 2021

## Bundoora household average income/yr in 2021

In [4]:
import pandas as pd
from pathlib import Path

file_path = r"C:\Users\samantha\Downloads\Bundoora avg inc.xlsx" 
df = pd.read_excel(file_path, sheet_name="G02") #read the Excel file & specify the sheet needed

print(df.head()) #print the first few rows of the dataframe to check if it was read correctly

  AUSTRALIAN BUREAU OF STATISTICS 2021 Census of Population and Housing  \
0             Bundoora (Vic.) (SAL20399) 17.2 sq Kms
1                                                NaN
2                  G02 SELECTED MEDIANS AND AVERAGES
3                                                NaN
4                                                NaN

   Unnamed: 1  Unnamed: 2 Unnamed: 3                   List of tables
0         NaN         NaN        NaN                   Find out more:
1         NaN         NaN        NaN                              Age
2         NaN         NaN        NaN   Total personal income (weekly)
3         NaN         NaN        NaN     Total family income (weekly)
4         NaN         NaN        NaN  Total household income (weekly)

In [9]:
# clean Bundoora G02 data & saving it to data/clean/
project_root = Path.cwd().parent
raw_csv = project_root / "data" / "raw" / "all_rows_G02.csv"
clean_csv = project_root / "data" / "clean" / "all_rows_G02_clean.csv"

g02 = pd.read_csv(raw_csv, header=None, dtype=str, keep_default_na=True) 

left = g02[[0, 1]].rename(columns={0: "metric", 1: "value"})
right = g02[[3, 4]].rename(columns={3: "metric", 4: "value"})
combined = pd.concat([left, right], ignore_index=True)

combined["metric"] = combined["metric"].astype(str).str.strip()
combined["value"] = combined["value"].astype(str).str.strip()
combined = combined.replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA, "NAN": pd.NA})
combined = combined.dropna(subset=["metric", "value"])
combined = combined[~combined["metric"].str.contains("AUSTRALIAN BUREAU|G02 SELECTED|Unnamed", na=False)]
combined["value"] = pd.to_numeric(combined["value"], errors="coerce")
cleaned = combined.dropna(subset=["value"]).reset_index(drop=True)

clean_csv.parent.mkdir(parents=True, exist_ok=True)
cleaned.to_csv(clean_csv, index=False)
cleaned.to_excel(clean_xlsx, index=False)

print(f"Saved {len(cleaned)} rows to {clean_csv}")
display(cleaned)

Saved 8 rows to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\clean\all_rows_G02_clean.csv

                                     metric   value
0                     Median age of persons    38.0
1   Median total personal income ($/weekly)   690.0
2     Median total family income ($/weekly)  1991.0
3  Median total household income ($/weekly)  1668.0
4     Median mortgage repayment ($/monthly)  2000.0
5                 Median rent ($/weekly)(a)   381.0
6     Average number of persons per bedroom     0.8
7                    Average household size     2.6

## Sunshine household average income/yr in 2021

In [12]:
# generate and clean Sunshine G02 output (removing NaN/blank values)

import pandas as pd
from pathlib import Path

file_path = r"C:\Users\samantha\Downloads\GCP_SAL22395.xlsx" 
raw_g02 = pd.read_excel(file_path, sheet_name="G02", header=None, dtype=str)

left = raw_g02[[0, 1]].rename(columns={0: "metric", 1: "value"})
right = raw_g02[[3, 4]].rename(columns={3: "metric", 4: "value"})
combined = pd.concat([left, right], ignore_index=True)

combined["metric"] = combined["metric"].str.strip()
combined["value"] = combined["value"].str.strip()
combined = combined.replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA, "NAN": pd.NA})
combined = combined.dropna(subset=["metric", "value"])

combined = combined[
    ~combined["metric"].str.contains(
        r"AUSTRALIAN BUREAU|G02 SELECTED|List of tables|sq Kms|Unnamed",
        case=False,
        na=False,
    )
]

combined["value"] = pd.to_numeric(combined["value"], errors="coerce")
sunshine_clean = combined.dropna(subset=["value"]).reset_index(drop=True)

project_root = Path.cwd().parent
clean_csv = project_root / "data" / "clean" / "sunshine_G02_clean.csv"
clean_csv.parent.mkdir(parents=True, exist_ok=True)

sunshine_clean.to_csv(clean_csv, index=False)

print(f"Saved {len(sunshine_clean)} rows to {clean_csv}")
print("NaN count by column:")
print(sunshine_clean.isna().sum())
assert sunshine_clean.isna().sum().sum() == 0, "NaN values still exist in cleaned output"

display(sunshine_clean)

Saved 8 rows to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\clean\sunshine_G02_clean.csv
NaN count by column:
metric    0
value     0
dtype: int64

                                     metric   value
0                     Median age of persons    35.0
1   Median total personal income ($/weekly)   706.0
2     Median total family income ($/weekly)  1806.0
3  Median total household income ($/weekly)  1566.0
4     Median mortgage repayment ($/monthly)  1842.0
5                 Median rent ($/weekly)(a)   340.0
6     Average number of persons per bedroom     0.9
7                    Average household size     2.6

In [14]:
# saving Sunshine G02 to data/raw/
from pathlib import Path
import pandas as pd

file_path = r"C:\Users\samantha\Downloads\GCP_SAL22395.xlsx"
raw_g02 = pd.read_excel(file_path, sheet_name="G02", header=None, dtype=str)

project_root = Path.cwd().parent
raw_dir = project_root / "data" / "raw"
raw_dir.mkdir(parents=True, exist_ok=True)

raw_csv = raw_dir / "sunshine_G02_raw.csv"

raw_g02.to_csv(raw_csv, index=False, header=False)

print(f"Saved raw Sunshine G02 to {raw_csv}")
print(raw_g02.head())

Saved raw Sunshine G02 to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\raw\sunshine_G02_raw.csv
                                                   0    1    2    3  \
0  AUSTRALIAN BUREAU OF STATISTICS 2021 Census of...  NaN  NaN  NaN
1              Sunshine (Vic.) (SAL22395) 4.7 sq Kms  NaN  NaN  NaN
2                                                NaN  NaN  NaN  NaN
3                  G02 SELECTED MEDIANS AND AVERAGES  NaN  NaN  NaN
4                                                NaN  NaN  NaN  NaN

                                4
0                  List of tables
1                  Find out more:
2                             Age
3  Total personal income (weekly)
4    Total family income (weekly)

## Brunswick household average income/yr in 2021

In [15]:
# generate and clean Brunswick G02 output (removing NaN/blank values)

import pandas as pd
from pathlib import Path

file_path = r"C:\Users\samantha\Downloads\GCP_SAL20361.xlsx"
raw_g02 = pd.read_excel(file_path, sheet_name="G02", header=None, dtype=str)

left = raw_g02[[0, 1]].rename(columns={0: "metric", 1: "value"})
right = raw_g02[[3, 4]].rename(columns={3: "metric", 4: "value"})
combined = pd.concat([left, right], ignore_index=True)

combined["metric"] = combined["metric"].str.strip()
combined["value"] = combined["value"].str.strip()
combined = combined.replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA, "NAN": pd.NA})
combined = combined.dropna(subset=["metric", "value"])

combined = combined[
    ~combined["metric"].str.contains(
        r"AUSTRALIAN BUREAU|G02 SELECTED|List of tables|sq Kms|Unnamed",
        case=False,
        na=False,
    )
]

combined["value"] = pd.to_numeric(combined["value"], errors="coerce")
brunswick_clean = combined.dropna(subset=["value"]).reset_index(drop=True)

project_root = Path.cwd().parent
clean_csv = project_root / "data" / "clean" / "brunswick_G02_clean.csv"
clean_csv.parent.mkdir(parents=True, exist_ok=True)

brunswick_clean.to_csv(clean_csv, index=False)

print(f"Saved {len(brunswick_clean)} rows to {clean_csv}")
print("NaN count by column:")
print(brunswick_clean.isna().sum())
assert brunswick_clean.isna().sum().sum() == 0, "NaN values still exist in cleaned output"

display(brunswick_clean)

Saved 8 rows to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\clean\brunswick_G02_clean.csv
NaN count by column:
metric    0
value     0
dtype: int64

                                     metric   value
0                     Median age of persons    34.0
1   Median total personal income ($/weekly)  1085.0
2     Median total family income ($/weekly)  2807.0
3  Median total household income ($/weekly)  2096.0
4     Median mortgage repayment ($/monthly)  2162.0
5                 Median rent ($/weekly)(a)   441.0
6     Average number of persons per bedroom     0.9
7                    Average household size     2.1

In [16]:
# saving Brunswick G02 to data/raw/
from pathlib import Path
import pandas as pd

file_path = r"C:\Users\samantha\Downloads\GCP_SAL20361.xlsx"
raw_g02 = pd.read_excel(file_path, sheet_name="G02", header=None, dtype=str)

project_root = Path.cwd().parent
raw_dir = project_root / "data" / "raw"
raw_dir.mkdir(parents=True, exist_ok=True)

raw_csv = raw_dir / "brunswick_G02_raw.csv"

raw_g02.to_csv(raw_csv, index=False, header=False)

print(f"Saved raw Brunswick G02 to {raw_csv}")
print(raw_g02.head())

Saved raw Brunswick G02 to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\raw\brunswick_G02_raw.csv
                                                   0    1    2    3  \
0  AUSTRALIAN BUREAU OF STATISTICS 2021 Census of...  NaN  NaN  NaN
1               Brunswick (Vic.) (SAL20361) 5 sq Kms  NaN  NaN  NaN
2                                                NaN  NaN  NaN  NaN
3                  G02 SELECTED MEDIANS AND AVERAGES  NaN  NaN  NaN
4                                                NaN  NaN  NaN  NaN

                                4
0                  List of tables
1                  Find out more:
2                             Age
3  Total personal income (weekly)
4    Total family income (weekly)

## Coburg household average income/yr in 2021

In [23]:
# generate and clean Coburg I04 output (removing NaN/blank values)

import pandas as pd
from pathlib import Path

file_path = r"C:\Users\samantha\Downloads\IP_ILOC20101503.xlsx"
raw_i04 = pd.read_excel(file_path, sheet_name="I04", header=None, dtype=str)

project_root = Path.cwd().parent
raw_dir = project_root / "data" / "raw"
clean_dir = project_root / "data" / "clean"
raw_dir.mkdir(parents=True, exist_ok=True)
clean_dir.mkdir(parents=True, exist_ok=True)

raw_csv = raw_dir / "coburg_I04_raw.csv"
clean_csv = clean_dir / "coburg_I04_clean.csv"

# saving raw Coburg I04 to data/raw/

raw_i04.to_csv(raw_csv, index=False, header=False)

pairs = []
cols = set(raw_i04.columns.tolist())
if {0, 1}.issubset(cols):
    pairs.append((0, 1))
if {3, 4}.issubset(cols):
    pairs.append((3, 4))
elif {2, 3}.issubset(cols):
    pairs.append((2, 3))

if not pairs:
    raise ValueError("Could not find expected metric/value column pairs in I04 sheet.")

frames = [
    raw_i04[[m, v]].rename(columns={m: "metric", v: "value"})
    for m, v in pairs
]
combined = pd.concat(frames, ignore_index=True)

combined["metric"] = combined["metric"].astype(str).str.strip()
combined["value"] = combined["value"].astype(str).str.strip()
combined = combined.replace({"": pd.NA, "nan": pd.NA, "NaN": pd.NA, "NAN": pd.NA})
combined = combined.dropna(subset=["metric", "value"])

combined = combined[
    ~combined["metric"].str.contains(
        r"AUSTRALIAN BUREAU|I04 SELECTED|List of tables|sq Kms|Unnamed",
        case=False,
        na=False,
    )
]

combined["value"] = pd.to_numeric(combined["value"], errors="coerce")
coburg_clean = combined.dropna(subset=["value"]).reset_index(drop=True)

coburg_clean.to_csv(clean_csv, index=False)

print(f"Saved raw Coburg I04 to {raw_csv}")
print(f"Saved {len(coburg_clean)} cleaned rows to {clean_csv}")
print("NaN count by column:")
print(coburg_clean.isna().sum())
assert coburg_clean.isna().sum().sum() == 0, "NaN values still exist in cleaned output"

display(coburg_clean.head())

Saved raw Coburg I04 to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\raw\coburg_I04_raw.csv
Saved 16 cleaned rows to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\clean\coburg_I04_clean.csv
NaN count by column:
metric    0
value     0
dtype: int64

                                     metric   value
0                     Median age of persons    26.0
1   Median total personal income ($/weekly)   825.0
2  Median total household income ($/weekly)  2110.0
3     Median mortgage repayment ($/monthly)  2000.0
4                 Median rent ($/weekly)(c)   421.0

## Combined table: median total household income ($/weekly)

In [24]:
# merge cleaned datasets and keep only median total household income ($/weekly)

from pathlib import Path
import pandas as pd

project_root = Path.cwd().parent
clean_dir = project_root / "data" / "clean"

target_metric = "Median total household income ($/weekly)"
files = {
    "Bundoora": "all_rows_G02_clean.csv",
    "Sunshine": "sunshine_G02_clean.csv",
    "Brunswick": "brunswick_G02_clean.csv",
    "Coburg": "coburg_I04_clean.csv",
}

rows = []
for suburb, filename in files.items():
    df = pd.read_csv(clean_dir / filename)
    metric_mask = df["metric"].astype(str).str.strip().str.casefold() == target_metric.casefold()
    match = df.loc[metric_mask, "value"]

    if match.empty:
        income_value = pd.NA
    else:
        income_value = pd.to_numeric(match.iloc[0], errors="coerce")

    rows.append(
        {
            "Suburb": suburb,
            "Median total household income ($/weekly)": income_value,
        }
    )

income_table = pd.DataFrame(rows).sort_values("Suburb").reset_index(drop=True)

display(income_table)

      Suburb  Median total household income ($/weekly)
0  Brunswick                                    2096.0
1   Bundoora                                    1668.0
2     Coburg                                    2110.0
3   Sunshine                                    1566.0

In [26]:
# convert weekly household income to annual household income

weekly_col = "Median total household income ($/weekly)"
annual_col = "Annual total household income ($/year)"

annual_income_table = income_table.copy()
annual_income_table[annual_col] = pd.to_numeric(annual_income_table[weekly_col], errors="coerce") * 52
annual_income_table = annual_income_table[["Suburb", annual_col]].sort_values("Suburb").reset_index(drop=True)

# save annual income table to data/clean/

output_csv = project_root / "data" / "clean" / "annual_household_income_table.csv"
annual_income_table.to_csv(output_csv, index=False)

print(f"Saved annual income table to {output_csv}")
display(annual_income_table)

Saved annual income table to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\clean\annual_household_income_table.csv

      Suburb  Annual total household income ($/year)
0  Brunswick                                108992.0
1   Bundoora                                 86736.0
2     Coburg                                109720.0
3   Sunshine                                 81432.0

# Distance to Upfield line/km

Distance data were obtained manually from Google Maps by entering suburb-to-location directions; raw data are not included due to the lack of direct export functionality.

In [ ]:
from pathlib import Path
import pandas as pd

rows = [
    {"origin": "Bundoora", "destination_station": "Upfield line", "distance_km": 14.4},
    {"origin": "Sunshine", "destination_station": "Upfield line", "distance_km": 10.3},
    {"origin": "Coburg", "destination_station": "Upfield line", "distance_km": 0.0},
    {"origin": "Brunswick", "destination_station": "Upfield line", "distance_km": 0.0},
]

distance_to_upfield_df = pd.DataFrame(rows)
distance_to_upfield_df["distance_km_squared"] = (distance_to_upfield_df["distance_km"] ** 2).round(3)

project_root = Path.cwd().parent
output_path = project_root / "data" / "clean" / "bundoora_sunshine_to_upfield_driving_distances.csv"
distance_to_upfield_df.to_csv(output_path, index=False)

print(f"Saved: {output_path}")
distance_to_upfield_df

Saved: c:\Users\samantha\Desktop\ECC3479 PROJECT\data\clean\bundoora_sunshine_to_upfield_driving_distances.csv

      origin destination_station  distance_km  distance_km_squared
0   Bundoora        Upfield line         14.4               207.36
1   Sunshine        Upfield line         10.3               106.09
2     Coburg        Upfield line          0.0                 0.00
3  Brunswick        Upfield line          0.0                 0.00

# Annual house pricing from 2015 to 2024

In 2020, the Level Crossing Removal Project (LXRP) removed four dangerous level crossings in Coburg and Brunswick. Therefore, 2020 is taken as the completion year, with the analysis covering five years before and five years after this date.

In [ ]:
# generate and clean house price data for all 4 suburbs 

from pathlib import Path
import pandas as pd

project_root = Path.cwd().parent
file_path = project_root / "data" / "raw" / "houses-by-suburb-2014-2024.xlsx"

df = pd.read_excel(file_path, sheet_name="Table 1", header=None)

year_cols = {
    2015: 8,
    2016: 11,
    2017: 14,
    2018: 18,
    2019: 21,
    2020: 24,
    2021: 27,
    2022: 30,
    2023: 33,
    2024: 37,
}

suburb_names = {
    "COBURG": "Coburg",
    "BRUNSWICK": "Brunswick",
    "BUNDOORA": "Bundoora",
    "SUNSHINE": "Sunshine",
}

rows = df[df[0].astype(str).str.strip().str.upper().isin(suburb_names)].copy()
rows["Suburb"] = rows[0].astype(str).str.strip().str.upper().map(suburb_names)

house_prices = rows[["Suburb"] + [year_cols[year] for year in range(2015, 2025)]].copy()
house_prices.columns = ["Suburb"] + [str(year) for year in range(2015, 2025)]
house_prices = house_prices.reset_index(drop=True)

output_csv = project_root / "data" / "clean" / "house_prices_2015_2024.csv"
house_prices.to_csv(output_csv, index=False)

print(f"Saved {len(house_prices)} rows to {output_csv}")
display(house_prices)

Saved 4 rows to c:\Users\samantha\Desktop\ECC3479 PROJECT\data\clean\house_prices_2015_2024.csv

,Suburb,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Brunswick,861000,947000,1200000,1100000,1037500,1100000,1350000,1330000,1300000,1300000
1,Bundoora,600500,652000,753000,730000,732500,745000,865000,853000,855000,865000
2,Coburg,778000,876000,1000000,966500,935500,1085000,1257500,1213000,1183000,1150000
3,Sunshine,530500,675000,765000,742000,720000,750000,870000,856500,800000,820000

## Summary table

In [6]:
from pathlib import Path
import pandas as pd

project_root = Path.cwd()
if not (project_root / "data" / "clean").exists():
    project_root = project_root.parent
clean_dir = project_root / "data" / "clean"

income = pd.read_csv(clean_dir / "annual_household_income_table.csv")
distance = pd.read_csv(clean_dir / "bundoora_sunshine_to_upfield_driving_distances.csv")
density = pd.read_csv(clean_dir / "all_suburbs_density.csv")
density["Year"] = pd.to_numeric(density["Year"], errors="coerce").astype("Int64")
density = density.rename(columns={"SA2 name": "Suburb"})
density["Suburb"] = density["Suburb"].replace(
    {
        "Bundoora - East": "Bundoora",
        "Brunswick East": "Brunswick",
        "Coburg - East": "Coburg",
    }
)
house_prices = pd.read_csv(clean_dir / "house_prices_2015_2024.csv")

density_2025 = (
    density[density["Year"] == 2025][["Suburb", "Density"]]
    .drop_duplicates(subset=["Suburb"])
    .rename(columns={"Density": "Population Density (2025 only)"})
)

income_summary = income.rename(
    columns={"Annual total household income ($/year)": "Household Average Income per year"}
)

distance_summary = distance[["origin", "distance_km"]].rename(
    columns={"origin": "Suburb", "distance_km": "Distance to Upfield Line (km)"}
)

house_price_cols = ["Suburb"] + [str(year) for year in range(2015, 2025)]
house_price_summary = house_prices[house_price_cols].rename(
    columns={str(year): f"Housing Price {year}" for year in range(2015, 2025)}
)

combined_table = (
    income_summary.merge(density_2025, on="Suburb", how="left")
    .merge(distance_summary, on="Suburb", how="left")
    .merge(house_price_summary, on="Suburb", how="left")
)

combined_table = combined_table[
    [
        "Suburb",
        "Household Average Income per year",
        "Population Density (2025 only)",
        "Distance to Upfield Line (km)",
        "Housing Price 2015",
        "Housing Price 2016",
        "Housing Price 2017",
        "Housing Price 2018",
        "Housing Price 2019",
        "Housing Price 2020",
        "Housing Price 2021",
        "Housing Price 2022",
        "Housing Price 2023",
        "Housing Price 2024",
    ]
].sort_values(["Suburb"]).reset_index(drop=True)

output_csv = clean_dir / "suburb_summary_table.csv"
combined_table.to_csv(output_csv, index=False)

print(f"Saved combined table to {output_csv}")
display(combined_table)

Saved combined table to c:\Users\samantha\Desktop\ECC3479-project\ecc3479-project\ECC3479-project\data\clean\suburb_summary_table.csv

,Suburb,Household Average Income per year,Population Density (2025 only),Distance to Upfield Line (km),Housing Price 2015,Housing Price 2016,Housing Price 2017,Housing Price 2018,Housing Price 2019,Housing Price 2020,Housing Price 2021,Housing Price 2022,Housing Price 2023,Housing Price 2024
0,Brunswick,108992.0,2825.576923,0.0,861000,947000,1200000,1100000,1037500,1100000,1350000,1330000,1300000,1300000
1,Bundoora,86736.0,689.266667,14.4,600500,652000,753000,730000,732500,745000,865000,853000,855000,865000
2,Coburg,109720.0,2065.285714,0.0,778000,876000,1000000,966500,935500,1085000,1257500,1213000,1183000,1150000
3,Sunshine,81432.0,1390.547945,10.3,530500,675000,765000,742000,720000,750000,870000,856500,800000,820000

## Suburbs (new) with removed level crossings to closest LXRP site (km)

In [2]:
import pandas as pd

suburbs = [
    ("Chelsea", 4),
    ("Laverton", 3),
    ("Ringwood", 2),
    ("Mentone", 2),
    ("Preston", 1),
    ("Blackburn", 2),
    ("Beaconsfield", 2),
    ("Essendon", 1),
    ("Glen Iris", 1),
    ("Cranbourne", 3),
    ("Campbellfield", 3),
    ("Pakenham", 3),
    ("Lilydale", 2),
    ("Bentleigh", 1),
    ("Clayton", 2),
    ("Noble Park", 2),
    ("Cheltenham", 2),
    ("Werribee", 3),
    ("Berwick", 3),
    ("Croydon", 0),
    ("Noble Park", 0),
    ("Edithvale", 2),
    ("Williamstown", 1),
    ("Ardeer", 1),
    ("St Albans", 1),
    ("Sunbury", 2),
    ("Glenroy", 0),
    ("Alphington", 1),
    ("Carnegie", 1),
    ("Hallam", 3),
    ("Mitcham", 2),
    ("Reservoir", 0),
    ("Coburg", 0),
    ("Brunswick", 0),
    ("Bundoora", 4),
    ("Doncaster", 10),
    ("Doncaster East", 12),
    ("Donvale", 9),
    ("Templestowe", 8),
    ("Templestowe Lower", 6),
    ("Warrandyte", 12),
    ("Wonga Park", 15),
    ("Park Orchards", 9),
    ("Bulleen", 10),
    ("Rowville", 10),
    ("Lysterfield", 11),
    ("Scoresby", 9),
    ("Knoxfield", 9),
    ("Wantirna", 6),
    ("Wantirna South", 7),
    ("The Basin", 7),
    ("Endeavour Hills", 6),
    ("Doveton", 4),
    ("Greenvale", 7),
    ("Gladstone Park", 6),
    ("Westmeadows", 3),
    ("Tullamarine", 6),
    ("Keilor East", 4),
]

suburb_table = pd.DataFrame(
    suburbs,
    columns=["Suburb", "nearest LXRP site"],
)
suburb_table = suburb_table.sort_values(
    by=["nearest LXRP site", "Suburb"],
    kind="mergesort",
).reset_index(drop=True)
display(suburb_table)

               Suburb  nearest LXRP site
0           Brunswick                  0
1              Coburg                  0
2             Croydon                  0
3             Glenroy                  0
4          Noble Park                  0
5           Reservoir                  0
6          Alphington                  1
7              Ardeer                  1
8           Bentleigh                  1
9            Carnegie                  1
10           Essendon                  1
11          Glen Iris                  1
12            Preston                  1
13          St Albans                  1
14       Williamstown                  1
15       Beaconsfield                  2
16          Blackburn                  2
17         Cheltenham                  2
18            Clayton                  2
19          Edithvale                  2
20           Lilydale                  2
21            Mentone                  2
22            Mitcham                  2
23         Noble Park                  2
24           Ringwood                  2
25            Sunbury                  2
26            Berwick                  3
27      Campbellfield                  3
28         Cranbourne                  3
29             Hallam                  3
30           Laverton                  3
31           Pakenham                  3
32           Werribee                  3
33        Westmeadows                  3
34           Bundoora                  4
35            Chelsea                  4
36            Doveton                  4
37        Keilor East                  4
38    Endeavour Hills                  6
39     Gladstone Park                  6
40  Templestowe Lower                  6
41        Tullamarine                  6
42           Wantirna                  6
43          Greenvale                  7
44          The Basin                  7
45     Wantirna South                  7
46        Templestowe                  8
47            Donvale                  9
48          Knoxfield                  9
49      Park Orchards                  9
50           Scoresby                  9
51            Bulleen                 10
52          Doncaster                 10
53           Rowville                 10
54        Lysterfield                 11
55     Doncaster East                 12
56         Warrandyte                 12
57         Wonga Park                 15

## House prices for suburbs with removed level crossings to closest LXRP site

In [5]:
from pathlib import Path
import pandas as pd

project_root = Path.cwd()
if not (project_root / "data" / "raw").exists():
    project_root = project_root.parent

excel_path = project_root / "data" / "raw" / "houses-by-suburb-2014-2024.xlsx"
output_csv = project_root / "data" / "clean" / "closest_lxrp_site_house_prices_2015_2024.csv"
output_csv.parent.mkdir(parents=True, exist_ok=True)

year_cols = {
    2015: 8,
    2016: 11,
    2017: 14,
    2018: 18,
    2019: 21,
    2020: 24,
    2021: 27,
    2022: 30,
    2023: 33,
    2024: 37,
}

raw_df = pd.read_excel(excel_path, sheet_name="Table 1", header=None)

lxrp_suburbs = suburb_table["Suburb"].dropna().astype(str).str.strip().unique().tolist()
suburb_lookup = {name.upper(): name for name in lxrp_suburbs}

rows = raw_df[raw_df[0].astype(str).str.strip().str.upper().isin(suburb_lookup)].copy()
rows["Suburb"] = rows[0].astype(str).str.strip().str.upper().map(suburb_lookup)

house_prices_lxrp = rows[["Suburb"] + [year_cols[year] for year in range(2015, 2025)]].copy()
house_prices_lxrp.columns = ["Suburb"] + [str(year) for year in range(2015, 2025)]

for col in [str(year) for year in range(2015, 2025)]:
    house_prices_lxrp[col] = (
        house_prices_lxrp[col]
        .astype(str)
        .str.extract(r"(\d+(?:\.\d+)?)", expand=False)
    )
    house_prices_lxrp[col] = pd.to_numeric(house_prices_lxrp[col], errors="coerce")

suburb_alias = {
    "Edithvalue": "Edithvale",
    "Tullarmarine": "Tullamarine",
}

manual_updates = {
    ("Berwick", "2017"): 670000,
    ("Berwick", "2020"): 700000,
    ("Blackburn", "2017"): 1410000,
    ("Blackburn", "2020"): 1405000,
    ("Edithvale", "2018"): 1047500,
    ("Edithvalue", "2020"): 1029500,
    ("Endeavour Hills", "2018"): 651000,
    ("Endeavour Hills", "2020"): 670000,
    ("Essendon", "2018"): 1691000,
    ("Essendon", "2020"): 1520000,
    ("Mitcham", "2017"): 264000,
    ("Werribee", "2017"): 403000,
    ("Werribee", "2022"): 610000,
    ("Westmeadows", "2017"): 566000,
    ("Westmeadows", "2022"): 700000,
    ("Williamstown", "2017"): 1440000,
    ("Williamstown", "2022"): 1647500,
    ("Wonga Park", "2020"): 1077500,
}

series_updates = {
    "Tullarmarine": [472500, 530000, 655000, 665500, 612000, 640000, 755000, 760000, 720000, 739000],
    "Wantirna": [764000, 801000, 953000, 906500, 850000, 907000, 1065000, 1102500, 1150000, 1085000],
    "Wantirna South": [829000, 875000, 1005000, 1000000, 988500, 1015000, 1223500, 1225000, 1333000, 1265000],
    "Warrandyte": [829000, 890000, 1042500, 1110000, 994000, 996000, 1285000, 1300000, 1271000, 1360000],
}

years = [str(year) for year in range(2015, 2025)]

for (suburb_name, year), value in manual_updates.items():
    resolved_suburb = suburb_alias.get(suburb_name, suburb_name)
    row_mask = house_prices_lxrp["Suburb"].str.casefold() == resolved_suburb.casefold()
    if row_mask.any():
        house_prices_lxrp.loc[row_mask, year] = float(value)

for suburb_name, values in series_updates.items():
    resolved_suburb = suburb_alias.get(suburb_name, suburb_name)
    row_mask = house_prices_lxrp["Suburb"].str.casefold() == resolved_suburb.casefold()
    if row_mask.any():
        for year, value in zip(years, values):
            house_prices_lxrp.loc[row_mask, year] = float(value)

house_prices_lxrp = house_prices_lxrp.sort_values("Suburb").reset_index(drop=True)
house_prices_lxrp.to_csv(output_csv, index=False)

print(f"Saved {len(house_prices_lxrp)} rows to {output_csv}")
display(house_prices_lxrp)

Saved 57 rows to c:\Users\samantha\Desktop\uni ૮₍•᷄ ࡇ•᷅₎ა\Y3S1\ECC3479\ECC3479-project\ecc3479-project\ECC3479-project (data + GitHub repo)\data\clean\closest_lxrp_site_house_prices_2015_2024.csv

,Suburb,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Alphington,1296500.0,1272500.0,1560000.0,1612500.0,1455000.0,1865000.0,2253000.0,2195000.0,2110000.0,2080000.0
1,Ardeer,381500.0,517500.0,595000.0,629000.0,572000.0,615000.0,719000.0,682000.0,628500.0,680000.0
2,Beaconsfield,559000.0,585000.0,694500.0,730000.0,685000.0,711000.0,892000.0,940000.0,920000.0,990000.0
3,Bentleigh,1245000.0,1380000.0,1470000.0,1394000.0,1376000.0,1510000.0,1747000.0,1726500.0,1691000.0,1641500.0
4,Berwick,535000.0,583000.0,670000.0,690000.0,670000.0,700000.0,812000.0,870000.0,850000.0,870000.0
5,Blackburn,1200500.0,1241000.0,1410000.0,1370500.0,1305000.0,1405000.0,1639500.0,1549500.0,1569000.0,1517000.0
6,Brunswick,861000.0,947000.0,1200000.0,1100000.0,1037500.0,1100000.0,1350000.0,1330000.0,1300000.0,1300000.0
7,Bulleen,1095000.0,1170000.0,1300000.0,1230000.0,1105000.0,1177000.0,1355000.0,1386000.0,1400000.0,1300000.0
8,Bundoora,600500.0,652000.0,753000.0,730000.0,732500.0,745000.0,865000.0,853000.0,855000.0,865000.0
9,Campbellfield,374500.0,420000.0,507000.0,550000.0,533000.0,537500.0,602500.0,605000.0,605000.0,620000.0
10,Carnegie,1300000.0,1348500.0,1510000.0,1445000.0,1313500.0,1420000.0,1776000.0,1687500.0,1675000.0,1715000.0
11,Chelsea,730000.0,890000.0,914000.0,905000.0,856500.0,980000.0,1167500.0,1140000.0,1180000.0,1210000.0
12,Cheltenham,867000.0,942500.0,1170000.0,1105000.0,1035000.0,1130000.0,1306000.0,1350000.0,1335000.0,1332500.0
13,Clayton,976000.0,1010500.0,1250000.0,1255000.0,1158000.0,1055000.0,1200000.0,1105000.0,1170000.0,1165000.0
14,Coburg,778000.0,876000.0,1000000.0,966500.0,935500.0,1085000.0,1257500.0,1213000.0,1183000.0,1150000.0
15,Cranbourne,360000.0,406000.0,510000.0,540000.0,500000.0,510000.0,618000.0,660000.0,655000.0,660000.0
16,Croydon,605000.0,695000.0,809000.0,792500.0,735000.0,785000.0,920000.0,900000.0,920000.0,923000.0
17,Doncaster,1176000.0,1297500.0,1368000.0,1320000.0,1270000.0,1280000.0,1500000.0,1500000.0,1547500.0,1480500.0
18,Doncaster East,1113500.0,1230000.0,1360000.0,1222000.0,1198000.0,1255000.0,1493500.0,1533000.0,1630000.0,1603500.0
19,Donvale,964000.0,970000.0,1200000.0,1182500.0,1140000.0,1195000.0,1337500.0,1440000.0,1438000.0,1514000.0
20,Doveton,348000.0,405000.0,490000.0,543500.0,472000.0,500000.0,579000.0,625000.0,561500.0,600000.0
21,Edithvale,766000.0,930000.0,1058500.0,1047500.0,950000.0,1029500.0,1240000.0,1330000.0,1270500.0,1310000.0
22,Endeavour Hills,496500.0,550000.0,630500.0,651000.0,625000.0,670000.0,745000.0,810000.0,790500.0,815000.0
23,Essendon,1228000.0,1365000.0,1400000.0,1691000.0,1450000.0,1520000.0,1750000.0,1845500.0,1795000.0,1741500.0
24,Gladstone Park,460000.0,525000.0,645000.0,630000.0,636500.0,640000.0,728000.0,730000.0,710000.0,712500.0
25,Glen Iris,1800000.0,1935000.0,2025000.0,1927500.0,1967000.0,2136000.0,2492500.0,2500000.0,2500000.0,2370000.0
26,Glenroy,560000.0,600000.0,730000.0,725000.0,700000.0,740000.0,835000.0,850000.0,792500.0,827000.0
27,Greenvale,500000.0,510000.0,650000.0,720000.0,715000.0,720000.0,820000.0,881000.0,840000.0,870000.0
28,Hallam,424000.0,455000.0,580000.0,630000.0,550000.0,600000.0,700000.0,720000.0,720000.0,750000.0
29,Keilor East,651000.0,720000.0,843000.0,830000.0,835000.0,842000.0,1000000.0,1000000.0,990000.0,1055000.0
30,Knoxfield,681000.0,741000.0,870000.0,815000.0,760000.0,810000.0,980000.0,965000.0,950000.0,931000.0
31,Laverton,377500.0,429000.0,535000.0,579000.0,529000.0,560000.0,605000.0,610000.0,582500.0,590000.0
32,Lilydale,534000.0,633500.0,710500.0,705000.0,675500.0,709000.0,840000.0,860000.0,925000.0,865000.0
33,Lysterfield,780000.0,857500.0,995500.0,976500.0,956500.0,1009500.0,1132000.0,1267500.0,1307500.0,1331000.0
34,Mentone,950000.0,982500.0,1097500.0,1080000.0,1031000.0,1050000.0,1370000.0,1475000.0,1332500.0,1320000.0
35,Mitcham,885500.0,941000.0,264000.0,998000.0,942000.0,1066500.0,1212500.0,1200000.0,1210000.0,1180000.0
36,Noble Park,510000.0,600000.0,680000.0,680000.0,625500.0,675000.0,751000.0,753500.0,732000.0,778500.0
37,Pakenham,367000.0,400000.0,470000.0,520000.0,485000.0,525000.0,600000.0,652000.0,640000.0,655000.0
38,Park Orchards,1225000.0,1335000.0,1450000.0,1480000.0,1510000.0,1530000.0,1920000.0,1965000.0,1740000.0,1936000.0
39,Preston,791000.0,882000.0,996000.0,980000.0,940000.0,1026000.0,1250000.0,1136000.0,1145000.0,1185000.0
40,Reservoir,615000.0,707500.0,812500.0,790000.0,754000.0,795000.0,945000.0,940000.0,870000.0,905000.0
41,Ringwood,777500.0,837500.0,910500.0,896500.0,801000.0,900000.0,1018000.0,1038000.0,999500.0,1025000.0
42,Rowville,710000.0,778000.0,867000.0,838000.0,815500.0,838000.0,1000000.0,1080000.0,1090000.0,1055000.0
43,Scoresby,661000.0,700000.0,878500.0,835000.0,766500.0,785000.0,950000.0,970500.0,955500.0,970000.0
44,St Albans,428000.0,500000.0,610000.0,626500.0,594000.0,600000.0,675000.0,682000.0,645000.0,652000.0
45,Sunbury,370000.0,395000.0,492000.0,546000.0,533500.0,571000.0,645000.0,670000.0,660000.0,665000.0
46,Templestowe,1180000.0,1260000.0,1415000.0,1308000.0,1292500.0,1381500.0,1603000.0,1628500.0,1695000.0,1650000.0
47,Templestowe Lower,1060000.0,1105500.0,1302000.0,1150000.0,1080000.0,1189000.0,1432500.0,1390000.0,1410000.0,1362000.0
48,The Basin,550000.0,595000.0,610000.0,682500.0,695000.0,739000.0,875000.0,864000.0,850000.0,881000.0
49,Tullamarine,472500.0,530000.0,655000.0,665500.0,612000.0,640000.0,755000.0,760000.0,720000.0,739000.0
50,Wantirna,764000.0,801000.0,953000.0,906500.0,850000.0,907000.0,1065000.0,1102500.0,1150000.0,1085000.0
51,Wantirna South,829000.0,875000.0,1005000.0,1000000.0,988500.0,1015000.0,1223500.0,1225000.0,1333000.0,1265000.0
52,Warrandyte,829000.0,890000.0,1042500.0,1110000.0,994000.0,996000.0,1285000.0,1300000.0,1271000.0,1360000.0
53,Werribee,335000.0,403000.0,403000.0,510000.0,500000.0,515500.0,570000.0,610000.0,610000.0,615000.0
54,Westmeadows,470000.0,500000.0,566000.0,620000.0,620000.0,605000.0,716000.0,700000.0,727500.0,670000.0
55,Williamstown,1120000.0,1282500.0,1440000.0,1415000.0,1350000.0,1402500.0,1585000.0,1647500.0,1605000.0,1597500.0
56,Wonga Park,735000.0,801000.0,962500.0,1150000.0,1102000.0,1077500.0,1248000.0,1415000.0,1265000.0,1330000.0

## Population density of (NEW) suburbs from 2015 to 2024

In [4]:
from pathlib import Path
import re
import pandas as pd

# -----------------------------
# 1) Suburb list (ordered)
# -----------------------------
BASE_SUBURBS = [
    "Chelsea", "Laverton", "Ringwood", "Mentone", "Preston", "Blackburn",
    "Beaconsfield", "Essendon", "Glen Iris", "Cranbourne", "Campbellfield",
    "Pakenham", "Lilydale", "Bentleigh", "Clayton", "Noble Park",
    "Cheltenham", "Werribee", "Berwick", "Croydon", "Edithvale",
    "Williamstown", "Ardeer", "St Albans", "Sunbury", "Glenroy",
    "Alphington", "Carnegie", "Hallam", "Mitcham", "Reservoir",
    "Coburg", "Brunswick", "Bundoora"
]

NEW_SUBURBS = [
    "Doncaster", "Doncaster East", "Donvale", "Templestowe", "Templestowe Lower",
    "Warrandyte", "Wonga Park", "Park Orchards", "Bulleen", "Rowville",
    "Lysterfield", "Scoresby", "Knoxfield", "Wantirna", "Wantirna South",
    "The Basin", "Endeavour Hills", "Doveton", "Greenvale", "Gladstone Park",
    "Westmeadows", "Tullamarine", "Keilor East"
]

def unique_in_order(items):
    seen, out = set(), []
    for x in items:
        x = str(x).strip()
        if x and x not in seen:
            seen.add(x)
            out.append(x)
    return out

SUBURBS = unique_in_order(BASE_SUBURBS + NEW_SUBURBS)

# -----------------------------
# 2) Explicit SA2 mapping
# -----------------------------
SA2_MAP = {
    "Chelsea": ["Chelsea - Bonbeach"],
    "Cheltenham": ["Highett (East) - Cheltenham", "Highett (West) - Cheltenham"],

    "Doncaster East": ["Doncaster East - North", "Doncaster East - South"],
    "Donvale": ["Donvale - Park Orchards"],
    "Park Orchards": ["Donvale - Park Orchards"],

    "Warrandyte": ["Warrandyte - Wonga Park"],
    "Wonga Park": ["Warrandyte - Wonga Park"],

    "Rowville": ["Rowville - Central", "Rowville - North", "Rowville - South"],
    "Scoresby": ["Knoxfield - Scoresby"],
    "Knoxfield": ["Knoxfield - Scoresby"],

    "Endeavour Hills": ["Endeavour Hills - North", "Endeavour Hills - South"],

    "Greenvale": ["Greenvale - Bulla"],
    "Gladstone Park": ["Gladstone Park - Westmeadows"],
    "Westmeadows": ["Gladstone Park - Westmeadows"],
}

YEARS = list(range(2015, 2025))

# -----------------------------
# 3) Paths
# -----------------------------
project_root = Path.cwd()
if not (project_root / "data" / "raw").exists():
    project_root = project_root.parent

pop_path = project_root / "data" / "raw" / "abs_population.xlsx"
sa2_area_path = project_root / "data" / "raw" / "SA2_2021_AUST.xlsx"

out_long = project_root / "data" / "clean" / "requested_suburbs_density_2015_2024_long.csv"
out_wide = project_root / "data" / "clean" / "requested_suburbs_density_2015_2024.csv"

# -----------------------------
# 4) Load population
# -----------------------------
hdr = pd.read_excel(pop_path, sheet_name="Table 1", header=None, nrows=6)
colnames = hdr.iloc[5, :10].tolist() + hdr.iloc[4, 10:].tolist()

pop = pd.read_excel(pop_path, sheet_name="Table 1", header=None, skiprows=6)
pop.columns = colnames

pop["S/T name"] = pop["S/T name"].astype(str).str.strip()
pop = pop[pop["S/T name"].eq("Victoria")].copy()  # IMPORTANT: keep only VIC

pop["SA2 code"] = pd.to_numeric(pop["SA2 code"], errors="coerce").astype("Int64")
pop["SA2 name"] = pop["SA2 name"].astype(str).str.strip()

for y in YEARS:
    pop[y] = pd.to_numeric(pop[y], errors="coerce")

# -----------------------------
# 5) Load SA2 areas
# -----------------------------
sa2 = pd.read_excel(
    sa2_area_path,
    usecols=["SA2_CODE_2021", "SA2_NAME_2021", "AREA_ALBERS_SQKM", "STATE_NAME_2021"]
)
sa2["STATE_NAME_2021"] = sa2["STATE_NAME_2021"].astype(str).str.strip()
sa2 = sa2[sa2["STATE_NAME_2021"].eq("Victoria")].copy()

sa2["SA2_CODE_2021"] = pd.to_numeric(sa2["SA2_CODE_2021"], errors="coerce").astype("Int64")
sa2["SA2_NAME_2021"] = sa2["SA2_NAME_2021"].astype(str).str.strip()
sa2 = sa2.rename(columns={"AREA_ALBERS_SQKM": "sa2_area_km2"})

# join area to population by SA2 code
pop = pop.merge(
    sa2[["SA2_CODE_2021", "sa2_area_km2"]],
    left_on="SA2 code",
    right_on="SA2_CODE_2021",
    how="left"
)

sa2_names_all = set(pop["SA2 name"].dropna().unique())

# -----------------------------
# 6) Robust SA2 resolver
# -----------------------------
def resolve_sa2_names(suburb):
    # 1) explicit mapping first
    if suburb in SA2_MAP:
        return SA2_MAP[suburb]

    # 2) exact match
    if suburb in sa2_names_all:
        return [suburb]

    # 3) ""<suburb> - ..."" prefix match
    starts_with_dash = sorted(
        [n for n in sa2_names_all if n.lower().startswith(suburb.lower() + " -")]
    )
    if len(starts_with_dash) >= 1:
        return starts_with_dash

    # 4) strict word-boundary match
    pattern = re.compile(rf"\b{re.escape(suburb)}\b", flags=re.IGNORECASE)
    matches = sorted([n for n in sa2_names_all if pattern.search(n)])

    if len(matches) == 0:
        raise ValueError(f"No SA2 match found for suburb: {suburb}")

    # If multiple in VIC, aggregate all
    return matches

# -----------------------------
# 7) Build density table
# -----------------------------
rows = []

for suburb in SUBURBS:
    sa2_names = resolve_sa2_names(suburb)
    sub = pop[pop["SA2 name"].isin(sa2_names)].copy()

    if sub.empty:
        continue

    # area: sum unique SA2 areas used for this suburb
    area_total = (
        sub[["SA2 code", "sa2_area_km2"]]
        .drop_duplicates()
        ["sa2_area_km2"]
        .sum(min_count=1)
    )

    if pd.isna(area_total) or area_total == 0:
        raise ValueError(f"Missing or zero area for suburb: {suburb} | SA2: {sa2_names}")

    for y in YEARS:
        pop_total = sub[y].sum(min_count=1)
        dens = pop_total / area_total if pd.notna(pop_total) else pd.NA

        rows.append({
            "Suburb": suburb,
            "Year": y,
            "Population": pop_total,
            "Area_km2": area_total,
            "Density": dens,
            "SA2_components": " | ".join(sa2_names),
        })

long_df = pd.DataFrame(rows)

# keep requested order
long_df["Suburb"] = pd.Categorical(long_df["Suburb"], categories=SUBURBS, ordered=True)
long_df = long_df.sort_values(["Suburb", "Year"]).reset_index(drop=True)

# -----------------------------
# 8) Save long
# -----------------------------
long_df.to_csv(out_long, index=False)

# -----------------------------
# 9) Save wide + numbering
# -----------------------------
wide = (
    long_df.pivot(index="Suburb", columns="Year", values="Density")
    .reindex(SUBURBS)
    .reset_index()
)
wide.columns = ["Suburb"] + [str(y) for y in YEARS]
wide.insert(0, "No.", range(1, len(wide) + 1))

wide.to_csv(out_wide, index=False)

print(f"Saved long: {out_long}")
print(f"Saved wide: {out_wide}")
print(f"Suburbs in wide: {wide['Suburb'].nunique()}")

pd.set_option("display.max_rows", None)
display(wide)

Saved long: c:\Users\samantha\Desktop\uni ૮₍•᷄ ࡇ•᷅₎ა\Y3S1\ECC3479\ECC3479-project\ecc3479-project\ECC3479-project (data + GitHub repo)\data\clean\requested_suburbs_density_2015_2024_long.csv
Saved wide: c:\Users\samantha\Desktop\uni ૮₍•᷄ ࡇ•᷅₎ა\Y3S1\ECC3479\ECC3479-project\ecc3479-project\ECC3479-project (data + GitHub repo)\data\clean\requested_suburbs_density_2015_2024.csv
Suburbs in wide: 57

,No.,Suburb,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,1,Chelsea,2654.619214,2735.201918,2776.507468,2804.720634,2824.451411,2844.550987,2824.451411,2828.508206,2870.735755,2921.261294
1,2,Laverton,374.644304,421.890664,461.000400,489.950596,516.922828,538.185938,523.396164,532.207093,555.583027,569.653542
2,3,Ringwood,1781.343020,1809.293174,1846.627314,1867.110640,1904.646587,1933.101256,1908.985420,1913.324252,1947.126785,1976.994097
3,4,Mentone,2995.955056,3077.528090,3097.528090,3104.044944,3119.775281,3113.707865,2989.438202,2999.325843,3079.101124,3133.707865
4,5,Preston,2936.200679,3010.447603,3047.129119,3064.099844,3080.628624,3095.743176,2989.410974,2986.317353,3097.069014,3172.023052
5,6,Blackburn,2538.454389,2589.688183,2625.819044,2642.199916,2664.041080,2675.774897,2597.239649,2590.617594,2660.091082,2720.270459
6,7,Beaconsfield,351.395326,405.891075,465.439410,533.619246,609.287736,673.106709,720.775452,774.429103,809.676905,851.300590
7,8,Essendon,3349.464029,3452.156543,3518.836339,3548.096672,3572.574065,3590.861773,3464.535914,3447.092254,3549.503418,3622.654250
8,9,Glen Iris,2993.041070,3011.796876,3042.296973,3053.340111,3069.466599,3045.627443,2980.946204,2956.230609,3015.127347,3065.960841
9,10,Cranbourne,1578.874645,1603.439011,1627.926614,1643.816688,1651.646580,1663.698472,1656.636217,1656.405926,1687.495202,1724.725570
10,11,Campbellfield,935.463828,941.457219,944.096510,944.921289,942.776864,928.425718,893.235166,871.955880,890.101008,901.153040
11,12,Pakenham,478.713406,507.982344,529.918555,549.024954,566.933330,582.022221,587.165457,597.679141,613.501304,627.805284
12,13,Lilydale,175.641812,177.799394,179.700992,181.218613,182.050562,182.407112,180.889491,181.886001,182.955650,187.343952
13,14,Bentleigh,3742.649658,3789.402654,3879.856046,3952.315157,4045.017834,4088.396902,4049.034414,4085.986954,4199.093859,4298.062402
14,15,Clayton,2943.877185,3009.397642,3137.569048,3233.936727,3308.065712,3354.216983,2935.507784,3080.896243,3386.977211,3581.386451
15,16,Noble Park,3721.924384,3796.909492,3864.769847,3914.409521,3956.223647,3952.719670,3819.218146,3794.573508,3912.190336,3959.610825
16,17,Cheltenham,2432.028682,2483.531805,2526.711910,2588.529885,2623.671518,2661.160670,2624.738572,2636.618436,2702.775762,2765.233969
17,18,Werribee,174.798319,179.199946,187.570254,198.301726,212.560913,227.581767,236.200618,247.048344,259.415393,269.866251
18,19,Berwick,1433.521468,1465.137315,1488.603556,1505.538553,1521.635470,1526.721749,1518.051955,1533.137396,1582.555219,1631.308359
19,20,Croydon,1927.081585,1982.330946,2019.790415,2047.851451,2069.266452,2078.664885,2046.307423,2039.997046,2091.419902,2143.782601
20,21,Edithvale,2578.772965,2622.693673,2634.850297,2671.908394,2710.339013,2701.515657,2680.143527,2675.241662,2723.279936,2767.004569
21,22,Williamstown,2178.783878,2230.918966,2246.164736,2267.127670,2286.184882,2267.672161,2188.176361,2198.930074,2253.787621,2295.985734
22,23,Ardeer,1729.834579,1787.590175,1793.474707,1793.256762,1783.449208,1761.436698,1654.207441,1626.528344,1676.437896,1717.411678
23,24,St Albans,2988.535410,3056.885010,3113.034910,3145.332833,3160.191441,3131.881882,3010.354104,2923.704955,2984.234234,3020.051301
24,25,Sunbury,101.660611,102.185510,102.957421,103.852837,105.265433,106.971355,106.431018,106.678029,109.588132,113.918550
25,26,Glenroy,2537.648732,2613.736425,2677.744914,2740.285837,2780.587478,2800.907634,2704.386896,2688.469441,2787.473753,2843.579960
26,27,Alphington,3165.702007,3269.677330,3283.194122,3263.092226,3281.114615,3305.722109,3143.174020,3168.474682,3281.807784,3345.579316
27,28,Carnegie,4900.775398,5018.004994,5069.785780,5138.914443,5174.398738,5171.770272,4939.151005,4970.429754,5271.651991,5476.935208
28,29,Hallam,1380.872587,1406.938497,1429.404828,1451.871160,1478.433563,1485.508596,1439.582945,1434.121517,1456.836095,1476.819959
29,30,Mitcham,2517.843401,2543.948333,2577.899836,2600.081484,2607.777157,2616.227309,2554.661918,2563.715652,2608.682531,2629.355223
30,31,Reservoir,2753.298781,2806.696408,2830.544907,2841.580068,2846.234709,2829.812716,2722.232973,2711.825404,2787.659448,2858.054360
31,32,Coburg,3954.028293,4009.113588,4032.041761,4048.769233,4041.270711,4007.094755,3873.130777,3888.704630,4031.609154,4131.973986
32,33,Brunswick,5211.278561,5334.953816,5388.818668,5469.713175,5514.438503,5514.632961,5111.327175,5150.802139,5479.824988,5747.204667
33,34,Bundoora,2122.202643,2176.828194,2181.145374,2188.105727,2178.502203,2160.176211,2077.621145,2077.444934,2138.678414,2192.334802
34,35,Doncaster,2402.151861,2494.358203,2588.046229,2648.339374,2755.020630,2862.841642,2869.110306,2921.425152,3061.729239,3171.601814
35,36,Doncaster East,2644.610344,2678.625777,2724.904667,2759.994271,2839.214423,2872.155683,2808.869076,2815.851191,2901.784915,2950.033120
36,37,Donvale,794.123868,803.497606,806.093411,807.775876,806.477974,801.238295,788.836118,787.874709,792.874036,805.083931
37,38,Templestowe,1088.871792,1097.061597,1098.984961,1096.937509,1096.565245,1088.747704,1061.014047,1063.185586,1081.364471,1080.744031
38,39,Templestowe Lower,2383.558414,2408.816893,2425.319099,2428.013336,2431.717913,2455.292493,2404.607146,2414.036978,2430.370794,2456.134442
39,40,Warrandyte,230.773770,231.932009,231.910156,231.429377,230.577087,227.364612,222.491264,220.196638,221.245610,223.168725
40,41,Wonga Park,230.773770,231.932009,231.910156,231.429377,230.577087,227.364612,222.491264,220.196638,221.245610,223.168725
41,42,Park Orchards,794.123868,803.497606,806.093411,807.775876,806.477974,801.238295,788.836118,787.874709,792.874036,805.083931
42,43,Bulleen,1724.453239,1733.597158,1736.595164,1743.490579,1742.741077,1747.387987,1704.366596,1711.711712,1743.190778,1758.330710
43,44,Rowville,1621.421304,1621.191126,1620.132306,1615.252529,1609.129788,1597.528807,1563.554504,1547.442030,1563.646575,1570.966242
44,45,Lysterfield,372.985833,374.013193,374.121337,374.121337,372.553261,367.794961,359.792365,354.277063,354.277063,355.953282
45,46,Scoresby,991.804836,1031.896286,1062.095892,1086.661732,1108.607215,1114.699543,1096.226032,1093.343640,1113.585892,1119.809238
46,47,Knoxfield,991.804836,1031.896286,1062.095892,1086.661732,1108.607215,1114.699543,1096.226032,1093.343640,1113.585892,1119.809238
47,48,Wantirna,1730.713667,1736.612732,1750.457479,1768.154676,1779.110084,1789.704324,1739.140903,1711.932967,1747.568140,1758.523548
48,49,Wantirna South,1380.438608,1391.145486,1392.493205,1393.766051,1394.814277,1392.792698,1355.131440,1345.248167,1359.399217,1374.673365
49,50,The Basin,773.752252,776.901142,780.224971,781.799416,779.350279,772.352746,766.229904,752.059899,751.710022,755.383727
50,51,Endeavour Hills,1326.693882,1328.837249,1328.637866,1327.391723,1322.855761,1311.092170,1278.592755,1263.838420,1271.813736,1280.137973
51,52,Doveton,2246.076827,2284.971599,2328.872629,2360.643112,2377.009724,2409.357851,2321.748339,2336.382016,2400.693174,2450.755752
52,53,Greenvale,162.961650,178.539403,190.467750,203.167685,211.947115,221.873501,233.624591,244.948178,256.188351,267.637061
53,54,Gladstone Park,1301.305970,1316.948909,1327.066590,1333.452928,1335.677382,1334.529277,1304.247991,1289.394374,1301.951780,1306.544202
54,55,Westmeadows,1301.305970,1316.948909,1327.066590,1333.452928,1335.677382,1334.529277,1304.247991,1289.394374,1301.951780,1306.544202
55,56,Tullamarine,1729.239539,1735.457961,1751.263117,1767.068273,1770.954787,1768.104677,1717.320896,1680.528566,1697.370126,1727.425832
56,57,Keilor East,2724.520318,2772.306121,2783.796600,2800.941125,2822.462975,2821.733421,2767.564018,2767.381630,2788.538703,2820.274312